#!/usr/bin/env node
/**
 * `figs` — the agent-side CLI (v1, zero-dependency).
 *
 *   figs status                         show login / workspace / agent state    [--json]
 *   figs login                          opens browser to approve (device flow) — agent never sees the token
 *   figs login <token>                  fallback: save a token you pasted (~/.figs/credentials.json)
 *   figs logout                         remove the locally-saved token (~/.figs/credentials.json)
 *   figs workspaces                     list the user's workspaces               [--json]
 *   figs init --workspace <slug-or-id> [--endpoint <url>]
 *                                         create .figs/config.json + GUIDE.md (generates a stable agent id)
 *   figs report --result '…'            record a run (stamps id/ts, --attach files, auto-push)
 *   figs ask <type> --title '…'         raise an ask (self-contained: options/details/attachments, auto-push)
 *   figs inbox [<ask-id>]               what needs you — answers/verdicts from your humans (pure read)
 *   figs resolve <ask-id>               close an ask (verbatim-checks --chosen; cites the Figs answer it acted on)
 *   figs doctor                         validate .figs/ against the spec before pushing
 *   figs push                           one-way push the .figs/ spine to the ingest endpoint
 *   figs version                        print the CLI version (and check for updates)
 *   figs help [<command>]               usage; `-h`/`--help` on any command, `-v` for version
 *
 * The writing verbs (report/ask/resolve) are sugar over the same files — they
 * stamp ids + real-clock timestamps, validate on write with teaching errors,
 * copy attachments into artifacts/, then invoke the same push as `figs push`
 * (auto-push IS push — one transport, many entry points; --no-push to batch).
 * Hand-writing the JSONL + bare `push` remains fully supported — files are the
 * protocol; the verbs are conveniences.
 *
 * Designed to be driven by an agent: non-interactive, clear output, `--json`
 * on read commands, `-h`/`--help`/`help` everywhere, and errors that say what to
 * do next. Bare `figs` prints help; unknown commands AND unknown flags exit
 * non-zero (no silent no-ops). Flags accept `--name value` or `--name=value`.
 * Network calls time out (30s) instead of hanging the agent.
 *
 * Auth is the *user* (a token, configured once per machine). Identity is the
 * *agent* — a UUID generated by `init`, stored in the committed, non-secret
 * .figs/config.json ({ endpoint, workspaceId, agentId }). Run from the
 * agent's repo root, where `.figs/` lives.
 */

import {
  appendFileSync,
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import { homedir } from "node:os"
import { basename, extname, join } from "node:path"
import { createHash, randomUUID } from "node:crypto"
import { spawn } from "node:child_process"

// Single source of truth for the version: package.json (shipped alongside this
// file in the published package). One edit keeps `figs version`, the floor
// check, and the npm package in lockstep.
const VERSION = JSON.parse(
  readFileSync(new URL("./package.json", import.meta.url), "utf8"),
).version
// Going-forward default; override with FIGS_ENDPOINT or .figs/config.json endpoint
// (e.g. FIGS_ENDPOINT=http://localhost:3000 for local dev).
const DEFAULT_ENDPOINT = "https://app.figs.so"

const repoDir = join(process.cwd(), ".figs")
const globalDir = join(homedir(), ".figs")
const globalCreds = join(globalDir, "credentials.json")
const cmd = process.argv[2] ?? "help"
const JSON_OUT = process.argv.includes("--json")
const WANTS_HELP = process.argv.slice(2).some((a) => a === "-h" || a === "--help")

/**
 * Command registry — single source for dispatch, `figs help`, and per-command
 * flag validation. `flags` lists the flags a command accepts (beyond the global
 * `-h`/`--help`); an unrecognized flag is rejected rather than silently ignored.
 */
const COMMANDS = {
  status: {
    args: "[--json]",
    flags: ["--json"],
    desc: "show login / workspace / agent state",
    eg: "figs status --json",
  },
  login: {
    args: "[<token>]",
    flags: [],
    desc: "log in — browser device-flow, or save a pasted token",
    more: [
      "no arg → device flow: opens a browser for a human to approve (you never see the token).",
      "<token> → save a token you already have to ~/.figs/credentials.json.",
    ],
    eg: "figs login",
  },
  logout: { args: "", flags: [], desc: "remove the locally-saved token (~/.figs/credentials.json)" },
  workspaces: {
    args: "[--json]",
    flags: ["--json"],
    desc: "list your workspaces (read-only; shows the slug)",
    eg: "figs workspaces",
  },
  init: {
    args: "[--workspace <slug-or-id>] [--endpoint <url>]",
    flags: ["--workspace", "--endpoint"],
    desc: "scaffold .figs/ here (identity + charter/contract/guide templates)",
    more: [
      "--workspace takes a slug (resolved to its UUID) or a raw UUID — get it from `figs workspaces`.",
      "Omit --workspace and (logged in) it uses your only workspace, or lists them so you can re-run with one.",
      "Never clobbers: an existing agent.json / CONTRACT.md / GUIDE.md / outbox is left exactly as-is.",
    ],
    eg: "figs init --workspace acme-corp",
  },
  report: {
    args: "--result <text> [options]",
    flags: [
      "--result", "--id", "--unit", "--period", "--status", "--trigger", "--attach", "--no-push",
    ],
    desc: "file a job's outcome — settles its row in runs.jsonl; stamps id/ts/state, pushes",
    more: [
      "One run = one JOB — a unit of work your manager would recognize; the runs",
      "list reads as the job list. Give a job a stable, meaningful --id",
      "(recon-acme-2026-11); reporting the same id again folds onto that job's row",
      "(progress evolves: blocked → ok). Sittings/sessions never mint runs —",
      "stopping to wait for a human is not a job.",
      "A report SETTLES the job (state: settled). A job that outlives a sitting",
      "should open with `figs checkpoint` first; a report with no prior checkpoint",
      "is simply a job born settled (the single-sitting case).",
      "--trigger '<what set this sitting in motion>' — state it in a fresh sitting",
      "('monthly close cron', 'Wayne, in chat'); omit when continuing one.",
      "You supply the content; the CLI does the bookkeeping (id, real-clock ts,",
      "validation, artifact copy, push).",
      "Single-quote prose values ('…') — inside double quotes your shell expands $,",
      "so \"($4,474.63)\" reaches figs as \"(,474.63)\": silent corruption.",
      "--attach <file> (repeatable) copies the file into artifacts/ and links it.",
      "--no-push writes locally only; `figs push` publishes later.",
      "Closing an ask is `figs resolve` — a close is not a job; never report one.",
      "Hand-writing runs.jsonl works too — this verb is sugar over the same file.",
    ],
    eg: "figs report --id recon-acme-2026-11 --result '88% matched · 31 flagged' --attach ./acme-2025-11.html",
  },
  checkpoint: {
    args: "--id <job> --note <text> [options]",
    flags: [
      "--id", "--note", "--trigger", "--status", "--unit", "--period", "--attach", "--no-push",
    ],
    desc: "save a job's progress mid-flight — folds onto its row, marks it in-flight, pushes",
    more: [
      "Your first checkpoint OPENS the job (state: in-flight) — make it the first",
      "act of any job that will outlive this sitting: say what triggered it",
      "(--trigger) and what you're setting out to do (--note). If you die mid-job,",
      "the checkpoint is what the next session finds in `figs inbox`; without one,",
      "the job never existed anywhere.",
      "Checkpoint at MANAGER grain — a step a human would recognize ('statements",
      "pulled — matching now'), never per tool call.",
      "--note is the job's current one-line state; it shows on the job's row and",
      "evolves with each fold. --status still carries the outcome look (a stuck",
      "job is --status warn — in-flight and warn are independent).",
      "`figs report --id <same-id>` settles the job when it's done — including",
      "abandoning it (--status warn --result 'abandoned — superseded by …').",
      "A checkpoint isn't a checkpoint until it's pushed — this verb pushes itself.",
    ],
    eg: "figs checkpoint --id recon-acme-2026-11 --note 'Statements pulled — matching now' --trigger 'monthly close cron'",
  },
  ask: {
    args: "<type> --title <text> [options]",
    flags: [
      "--id", "--title", "--need", "--found", "--option", "--on-approve", "--detail",
      "--attach", "--to", "--unit", "--run", "--stdin", "--no-push",
    ],
    desc: "raise an ask — one self-contained line in asks.jsonl, pushed so a human sees it",
    more: [
      "<type> = the answer contract: needs-decision (give me an answer) ·",
      "sign-off (give me a verdict) · fyi (no answer — a for-the-record note).",
      "Two strangers read every ask — a human deciding, a future session acting;",
      "the record must carry everything both need: --found (what you saw), --need",
      "(what you need), --option (repeatable; short, stable, quotable — answers cite",
      "one verbatim; the option is the label, context goes in --found/--detail),",
      "--detail 'Label=Value' (repeatable), --attach <file> (repeatable; a verdict",
      "blesses what the ask carries — attach the exact content for review + a brief:",
      "what to do once approved and what it requires).",
      "On a sign-off, --option entries are answer paths — the human's verdict can",
      "cite one verbatim ('Approved — file the 15 ready charges') — and",
      "--on-approve '<step>' (repeatable, ordered; sign-off only) states what",
      "approval sets in motion: an approval authorizes exactly the steps you stated.",
      "Flag anything irreversible in the step itself.",
      "--run <run-id> links the run this came out of — explicit id only (other",
      "sessions may report concurrently; `figs report` prints the id it wrote).",
      "--stdin reads a full JSON object instead of flags (long texts; attachments still via --attach).",
      "Single-quote prose values ('…') — double quotes let your shell eat $ amounts.",
    ],
    eg: "figs ask sign-off --title 'Send 10 payment reminders' --attach ./previews.html --on-approve 'Send the 10 reminder emails' --on-approve 'Mark the invoices chased' --run recon-2026-06",
  },
  inbox: {
    args: "[<ask-id>] [--json]",
    flags: ["--json"],
    desc: "what needs you — your humans' answers/verdicts on your asks (pure read)",
    more: [
      "Start every session with this. Bare: lists every ask with thread activity —",
      "answers and verdicts verbatim, plus the exact next command for each.",
      "With an ask id: the full handoff package — the ask, the whole thread, and its",
      "attached artifacts restored into .figs/artifacts/ (hash-verified) so a fresh",
      "session can act from the record alone.",
      "Scope: THIS agent's open asks + human-rejected ones you haven't acknowledged",
      "+ unfinished jobs (in-flight runs — your past self's work; finish or settle).",
      "Reads only — closing still happens via figs resolve / figs report.",
    ],
    eg: "figs inbox",
  },
  resolve: {
    args: "<ask-id> [--chosen <option>] [--by <who>] [--note <text>] [--withdrawn|--rejected]",
    flags: ["--chosen", "--by", "--note", "--withdrawn", "--rejected", "--no-push"],
    desc: "close an ask — appends the resolution fold line and pushes",
    more: [
      "--chosen must quote one of the ask's options[] verbatim (checked).",
      "Three closes, by who ended it: resolved (default — the need was met) ·",
      "--withdrawn (YOU retracted it; nobody acted) · --rejected (a HUMAN declined",
      "it — record their out-of-band no; rejected is terminal, re-raising = a new ask).",
      "After an answer, fork on what it unlocked: nothing new → resolve right away;",
      "real work → do the job, `figs report` it under its own id, THEN resolve —",
      "cite the job id in --note so a reader can find the work.",
    ],
    eg: "figs resolve acme-bridge --chosen 'Strip the alpha prefix' --by 'Sarah (accounting)'",
  },
  doctor: {
    args: "",
    flags: ["--json"],
    desc: "validate .figs/ against the spec without pushing — the conformance check for hand-authored or non-CLI setups",
  },
  push: {
    args: "",
    flags: [],
    desc: "publish .figs/ — spine to /api/ingest, artifacts to /api/artifacts",
    more: [
      "Idempotent (records fold by id). Exits non-zero if an artifact upload is rejected.",
      "The writing verbs (report/ask/resolve) call this automatically — you only need it",
      "after hand-editing files, after --no-push, or to retry a failed auto-push.",
    ],
    eg: "figs push",
  },
  version: { args: "", flags: [], desc: "print the CLI version and check for updates" },
  help: { args: "[<command>]", flags: [], desc: "show this help, or detailed help for one command" },
}

/** Reject unknown flags for a command (don't silently ignore an agent's typo). */
function checkFlags(name) {
  const allowed = new Set([...(COMMANDS[name].flags ?? []), "-h", "--help"])
  for (const tok of process.argv.slice(3)) {
    if (tok.startsWith("-") && tok !== "-" && tok !== "--") {
      const f = tok.split("=")[0]
      if (!allowed.has(f)) {
        die(`unknown flag "${f}" for \`figs ${name}\` — run \`figs ${name} --help\``)
      }
    }
  }
}

function die(msg) {
  console.error(`figs: ${msg}`)
  process.exit(1)
}
function readJson(path, fallback) {
  return existsSync(path) ? JSON.parse(readFileSync(path, "utf8")) : fallback
}
/** Read a flag value — supports both `--name value` and `--name=value`. */
function flag(name) {
  const args = process.argv.slice(2)
  for (let i = 0; i < args.length; i++) {
    if (args[i] === name) return args[i + 1]
    if (args[i].startsWith(`${name}=`)) return args[i].slice(name.length + 1)
  }
  return undefined
}
/** All values of a repeatable flag, in order. */
function flagAll(name) {
  const args = process.argv.slice(2)
  const out = []
  for (let i = 0; i < args.length; i++) {
    if (args[i] === name && args[i + 1] !== undefined) out.push(args[i + 1])
    else if (args[i].startsWith(`${name}=`)) out.push(args[i].slice(name.length + 1))
  }
  return out
}
/** Boolean flag — present or not (takes no value). */
function hasFlag(name) {
  return process.argv.slice(2).includes(name)
}
/** First non-flag token after the command (e.g. the ask type, the ask id). */
function positional() {
  const args = process.argv.slice(3)
  for (let i = 0; i < args.length; i++) {
    if (args[i].startsWith("-")) {
      // skip `--name value` pairs (but not `--name=value` or booleans)
      if (!args[i].includes("=") && !BOOLEAN_FLAGS.has(args[i])) i++
      continue
    }
    return args[i]
  }
  return undefined
}
const BOOLEAN_FLAGS = new Set([
  "--no-push", "--stdin", "--withdrawn", "--rejected", "--json", "-h", "--help",
])

/** ISO-8601 with the machine's real UTC offset (never the agent's guess). */
function nowIso() {
  const d = new Date()
  const pad = (n, w = 2) => String(Math.abs(n)).padStart(w, "0")
  const off = -d.getTimezoneOffset()
  const sign = off >= 0 ? "+" : "-"
  return (
    `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}` +
    `T${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}` +
    (off === 0 ? "Z" : `${sign}${pad(Math.trunc(off / 60))}:${pad(off % 60)}`)
  )
}
/** Generated unique id — stable/content-derived ids only via explicit --id. */
function genId(prefix) {
  return `${prefix}-${Date.now().toString(36)}${Math.random().toString(36).slice(2, 5)}`
}

// ---------- local validation (the spec's common mistakes, caught on write) ----
// The server's schema stays the source of truth; these catch what hand-authors
// and flag typos get wrong, with errors that teach the fix.
// Three types = three answer contracts: needs-decision (give me an answer) ·
// sign-off (give me a verdict) · fyi (no answer — a for-the-record note).
// "blocked" was folded into needs-decision in 0.6.0: a stuck JOB is the run's
// status, not an ask type; what you need from a human is a needs-decision.
const ASK_TYPES = ["needs-decision", "sign-off", "fyi"]
const RUN_STATUSES = ["ok", "warn", "fail"]
// Lifecycle, orthogonal to status (outcome): checkpoint stamps in-flight,
// report stamps settled. Absent = settled (a plain report is a complete fact).
const RUN_STATES = ["in-flight", "settled"]
const ASK_STATUSES = ["open", "resolved", "withdrawn", "rejected"]
const TO_VALUES = ["manager", "builder"]
const ARTIFACT_EXTS = new Set([
  ".html", ".md", ".txt", ".json", ".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg",
])
const ARTIFACT_MAX = 3 * 1024 * 1024

/** "signoff" → `did you mean "sign-off"?` — normalized nearest match. */
function didYouMean(value, allowed) {
  const norm = (s) => String(s).toLowerCase().replace(/[^a-z0-9]/g, "")
  const hit = allowed.find((a) => norm(a) === norm(value))
  return hit ? ` — did you mean "${hit}"?` : ` (valid: ${allowed.join(" · ")})`
}
function checkEnum(issues, obj, field, allowed, label) {
  const v = obj[field]
  if (v !== undefined && !allowed.includes(v)) {
    issues.push(`${label}.${field}: "${v}" isn't valid${didYouMean(v, allowed)}`)
  }
}
/** Validate one folded run record → array of issue strings. */
function validateRun(r) {
  const issues = []
  const label = `run "${r.id ?? "?"}"`
  if (!r.id || typeof r.id !== "string") issues.push(`${label}: missing required "id"`)
  if (!r.ts) issues.push(`${label}: missing required "ts" (ISO-8601 — \`figs report\` stamps it for you)`)
  checkEnum(issues, r, "status", RUN_STATUSES, label)
  checkEnum(issues, r, "state", RUN_STATES, label)
  if (r.artifact !== undefined && typeof r.artifact !== "string") {
    issues.push(`${label}.artifact: must be a single file name (use "artifacts" for a list)`)
  }
  if (r.artifacts !== undefined && (!Array.isArray(r.artifacts) || r.artifacts.some((a) => typeof a !== "string"))) {
    issues.push(`${label}.artifacts: must be an array of file names`)
  }
  return issues
}
/** Validate one folded ask record → array of issue strings. */
function validateAsk(a) {
  const issues = []
  const label = `ask "${a.id ?? "?"}"`
  if (!a.id || typeof a.id !== "string") issues.push(`${label}: missing required "id"`)
  if (!a.type) {
    issues.push(
      `${label}: missing required "type" — was it raised on another machine? (closing it from here needs the full record; cross-machine fetch is coming)`,
    )
  } else if (a.type === "blocked") {
    issues.push(
      `${label}.type: "blocked" was folded into needs-decision — a stuck job is the RUN's status (re-report --status onto the same job id); what you need from a human is a needs-decision ask`,
    )
  } else checkEnum(issues, a, "type", ASK_TYPES, label)
  if (!a.title) issues.push(`${label}: missing required "title"`)
  checkEnum(issues, a, "status", ASK_STATUSES, label)
  checkEnum(issues, a, "to", TO_VALUES, label)
  if (a.options !== undefined && (!Array.isArray(a.options) || a.options.some((o) => typeof o !== "string"))) {
    issues.push(`${label}.options: must be an array of short, quotable strings`)
  }
  if (a.onApprove !== undefined) {
    if (!Array.isArray(a.onApprove) || a.onApprove.some((s) => typeof s !== "string")) {
      issues.push(`${label}.onApprove: must be an array of strings — the ordered steps approval sets in motion`)
    } else if (a.type !== "sign-off") {
      issues.push(
        `${label}.onApprove: sign-off only — it is the approval contract; a ${a.type ?? "non-sign-off ask"} has no approval (the chosen option carries the next step)`,
      )
    }
  }
  if (a.details !== undefined && (!Array.isArray(a.details) || a.details.some((d) => !d || typeof d.l !== "string"))) {
    issues.push(`${label}.details: must be [{ "l": "Label", "v": "Value" }]`)
  }
  if (a.refs !== undefined && (!Array.isArray(a.refs) || a.refs.some((r) => !r || typeof r.label !== "string"))) {
    issues.push(`${label}.refs: must be [{ "label": "…", "artifact": "<file in artifacts/>" }]`)
  }
  return issues
}
/** Validate the whole local outbox (folded) — returns all issues. */
function validateOutbox(runs, asks) {
  return [...runs.flatMap(validateRun), ...asks.flatMap(validateAsk)]
}
function getToken() {
  return process.env.FIGS_TOKEN || readJson(globalCreds, {}).token
}
function resolveEndpoint() {
  const cfg = readJson(join(repoDir, "config.json"), {})
  return (process.env.FIGS_ENDPOINT || cfg.endpoint || DEFAULT_ENDPOINT).replace(
    /\/+$/,
    "",
  )
}
const REQUEST_TIMEOUT_MS = 30000
/** `fetch` with a hard timeout so a hung server never stalls the agent. */
async function fetchT(url, opts = {}) {
  const ctrl = new AbortController()
  const t = setTimeout(() => ctrl.abort(), REQUEST_TIMEOUT_MS)
  try {
    return await fetch(url, { ...opts, signal: ctrl.signal })
  } finally {
    clearTimeout(t)
  }
}
/** Human reason for a thrown fetch error (timeout vs. network). */
function netReason(e) {
  if (e?.name === "AbortError") return `timed out after ${REQUEST_TIMEOUT_MS / 1000}s`
  return e?.cause?.code || e?.code || e?.message || "network error"
}
/** Low-level request — returns { ok, status, data }, never throws/exits. */
async function request(method, path, body, token = getToken()) {
  const base = resolveEndpoint()
  let res
  try {
    res = await fetchT(`${base}${path}`, {
      method,
      headers: {
        "content-type": "application/json",
        ...(token ? { "x-figs-token": token } : {}),
      },
      body: body ? JSON.stringify(body) : undefined,
    })
  } catch (e) {
    // Unreachable host / DNS / timeout — degrade, don't crash.
    return { ok: false, status: 0, data: { error: `cannot reach ${base} (${netReason(e)})` } }
  }
  const text = await res.text()
  let data
  try {
    data = text ? JSON.parse(text) : {}
  } catch {
    data = { raw: text }
  }
  return { ok: res.ok, status: res.status, data }
}
/** Authenticated request that exits with a clear message on failure. */
async function api(method, path, body) {
  if (!getToken()) die("not logged in — run `figs login` (or set FIGS_TOKEN)")
  const r = await request(method, path, body)
  if (!r.ok) die(`${path} failed (${r.status}): ${r.data.error ?? r.data.raw ?? ""}`)
  return r.data
}

/**
 * Compare two semver strings → -1 | 0 | 1, or **null** if either is unparseable.
 * Returning null (rather than guessing) lets the caller skip the check instead of
 * failing closed on a malformed server-provided version — a bad `min` must never
 * lock an agent out of pushing.
 */
function cmpSemver(a, b) {
  const pa = String(a).split(".").map((n) => parseInt(n, 10))
  const pb = String(b).split(".").map((n) => parseInt(n, 10))
  for (let i = 0; i < 3; i++) {
    const x = pa[i] ?? 0
    const y = pb[i] ?? 0
    if (Number.isNaN(x) || Number.isNaN(y)) return null
    if (x !== y) return x < y ? -1 : 1
  }
  return 0
}
/**
 * Cached (daily) compatibility check — off the hot path. `hardFail` exits when
 * below the server's compatible `min`. Network failure is ignored (never blocks
 * on a transient outage).
 */
async function checkVersion({ force = false, hardFail = false } = {}) {
  const cachePath = join(globalDir, "version-check.json")
  let info = readJson(cachePath, {})
  const stale = !info.checkedAt || Date.now() - info.checkedAt > 86400000
  if (force || stale) {
    const r = await request("GET", "/api/version")
    if (r.ok) {
      info = { ...r.data, checkedAt: Date.now() }
      try {
        mkdirSync(globalDir, { recursive: true })
        writeFileSync(cachePath, JSON.stringify(info, null, 2) + "\n")
      } catch {
        /* cache best-effort */
      }
    }
  }
  const min = info?.cli?.min
  // cmpSemver returns null on an unparseable version → skip (never fail closed).
  if (min && cmpSemver(VERSION, min) === -1) {
    const msg = `figs CLI ${VERSION} is below the minimum ${min} — upgrade: npx @figs-so/cli@latest`
    if (hardFail) die(msg)
    console.warn(`figs: ! ${msg}`)
  }
}

/** `figs help [cmd]` — top-level usage, or one command's detail. */
function printHelp(name) {
  const pad = 36
  if (name && name !== "-h" && name !== "--help") {
    const c = COMMANDS[name]
    if (!c) {
      console.log(`figs: no such command "${name}"\n`)
      return printHelp()
    }
    console.log(`Usage: figs ${name}${c.args ? " " + c.args : ""}\n`)
    console.log(`  ${c.desc}`)
    if (c.more) for (const line of c.more) console.log(`  ${line}`)
    if (c.eg) console.log(`\n  e.g.  ${c.eg}`)
    return
  }
  console.log("figs — publish your AI agent's state to Figs (https://figs.so)\n")
  console.log("Usage: figs <command> [options]\n")
  console.log("Commands:")
  for (const [n, c] of Object.entries(COMMANDS)) {
    console.log(`  ${`${n} ${c.args}`.trim().padEnd(pad)} ${c.desc}`)
  }
  console.log("\nGlobal flags:")
  console.log(`  ${"-h, --help".padEnd(pad)} show help (or \`figs help <command>\`)`)
  console.log(`  ${"-v, --version".padEnd(pad)} print the CLI version`)
  console.log("\nEnvironment:")
  console.log(`  ${"FIGS_ENDPOINT".padEnd(pad)} override the API endpoint (e.g. http://localhost:3000)`)
  console.log(`  ${"FIGS_TOKEN".padEnd(pad)} use this token instead of ~/.figs/credentials.json`)
  console.log(`\nEndpoint: ${resolveEndpoint()}`)
  console.log(`Guide:    ${resolveEndpoint()}/llms.txt`)
}

if (cmd === "help" || cmd === "-h" || cmd === "--help") printHelp(process.argv[3])
else if (cmd === "version" || cmd === "--version" || cmd === "-v" || cmd === "-V") {
  console.log(VERSION)
  await checkVersion({ force: true })
} else if (WANTS_HELP) printHelp(cmd)
else if (COMMANDS[cmd]) {
  checkFlags(cmd) // reject unknown flags before running
  if (cmd === "login") await login(process.argv[3])
  else if (cmd === "logout") logout()
  else if (cmd === "status") await status()
  else if (cmd === "workspaces") await workspaces()
  else if (cmd === "init") await init()
  else if (cmd === "report") await reportCmd()
  else if (cmd === "checkpoint") await checkpointCmd()
  else if (cmd === "ask") await askCmd()
  else if (cmd === "inbox") await inboxCmd()
  else if (cmd === "resolve") await resolveCmd()
  else if (cmd === "doctor") await doctor()
  else if (cmd === "push") await push()
} else {
  console.error(`figs: unknown command "${cmd}" — run \`figs help\` for usage`)
  process.exit(1)
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms))
}
function saveToken(token) {
  // A bearer token must not be group/other-readable: dir 0700, file 0600.
  mkdirSync(globalDir, { recursive: true, mode: 0o700 })
  writeFileSync(globalCreds, JSON.stringify({ token }, null, 2) + "\n", { mode: 0o600 })
  // Enforce perms even if the dir/file pre-existed with looser modes (mode on
  // write only applies at creation).
  try {
    chmodSync(globalDir, 0o700)
    chmodSync(globalCreds, 0o600)
  } catch {
    /* best-effort — non-POSIX filesystems */
  }
}

// Best-effort: pop the approval page in the user's default browser so they only
// have to click Approve. Silent no-op when it can't (headless / remote / CI) —
// the link is always printed above as the fallback. Detached + unref'd so it
// never blocks or ties the polling loop to the browser process.
function openBrowser(url) {
  try {
    const [cmd, args] =
      process.platform === "darwin"
        ? ["open", [url]]
        : process.platform === "win32"
          ? ["cmd", ["/c", "start", "", url]]
          : ["xdg-open", [url]]
    const child = spawn(cmd, args, { stdio: "ignore", detached: true })
    child.on("error", () => {}) // swallow ENOENT / no opener available
    child.unref()
  } catch {
    /* ignore — the printed link is the fallback */
  }
}

/**
 * `figs login` → device flow: opens the approval page in the user's browser
 * (the printed link is the fallback); the human clicks Approve and the agent
 * never handles the token. `figs login <token>` → save a pasted token (fallback).
 */
async function login(token) {
  if (token) {
    saveToken(token)
    console.log("figs: ✓ token saved to ~/.figs/credentials.json")
    return
  }

  const start = await request("POST", "/api/device/start")
  if (!start.ok) die(`could not start login (${start.status})`)
  const d = start.data
  console.log("figs: opening your browser to approve this CLI — just click Approve there.")
  console.log(`        if it doesn't open, visit: ${d.verification_uri_complete}`)
  console.log(`        (or go to ${d.verification_uri} and enter code: ${d.user_code})`)
  openBrowser(d.verification_uri_complete)
  console.log("figs: waiting for approval…")

  const deadline = Date.now() + (d.expires_in ?? 600) * 1000
  const wait = (d.interval ?? 5) * 1000
  while (Date.now() < deadline) {
    await sleep(wait)
    const r = await request("POST", "/api/device/poll", { device_code: d.device_code })
    const status = r.data?.status
    if (status === "approved" && r.data.token) {
      saveToken(r.data.token)
      console.log("figs: ✓ authorized — token saved to ~/.figs/credentials.json")
      console.log("figs: next — run `figs init` to scaffold .figs/ here")
      return
    }
    if (status === "denied") die("authorization denied")
    if (status === "expired") die("code expired — run `figs login` again")
    if (status === "already_claimed") {
      die("this login was already completed (on another run) — run `figs status` to check; re-run `figs login` if no token was saved")
    }
    if (status === "not_found") die("login code not found — run `figs login` again")
    // pending → keep polling
  }
  die("timed out waiting for approval — run `figs login` again")
}

/**
 * `figs logout` — remove the locally-saved token (`~/.figs/credentials.json`).
 * This only clears *this machine's* copy; the token still exists server-side
 * until you revoke it in Settings. A token supplied via the FIGS_TOKEN env var
 * can't be removed here (unset the env var to fully log out).
 */
function logout() {
  if (existsSync(globalCreds)) {
    try {
      rmSync(globalCreds)
    } catch (e) {
      die(`could not remove ${globalCreds}: ${e?.message || e}`)
    }
    console.log("figs: ✓ logged out — removed ~/.figs/credentials.json")
  } else {
    console.log("figs: not logged in — no ~/.figs/credentials.json to remove")
  }
  if (process.env.FIGS_TOKEN) {
    console.warn(
      "figs: ! FIGS_TOKEN is still set in your environment — `unset FIGS_TOKEN` to fully log out",
    )
  }
  console.log(
    `        the token still exists server-side — revoke it at ${resolveEndpoint()}/settings`,
  )
}

/** Show where setup stands — login, workspace, charter. Drives the agent's next step. */
async function status() {
  const token = getToken()
  const cfg = readJson(join(repoDir, "config.json"), null)
  const hasAgent = existsSync(join(repoDir, "agent.json"))
  const hasContract = existsSync(join(repoDir, "CONTRACT.md"))
  const endpoint = resolveEndpoint()

  let loggedIn = false
  let list = null
  let account = null
  let unreachable = false
  if (token) {
    const r = await request("GET", "/api/workspaces", null, token)
    loggedIn = r.ok
    unreachable = r.status === 0
    if (r.ok) {
      list = r.data.workspaces ?? []
      account = r.data.user ?? null // null on a pre-account server
    }
  }

  if (JSON_OUT) {
    console.log(
      JSON.stringify(
        {
          version: VERSION,
          endpoint,
          loggedIn,
          account: account
            ? { id: account.id, email: account.email, name: account.name }
            : null,
          workspaces: list?.map((w) => ({ id: w.id, name: w.name, role: w.role })),
          config: cfg ? { workspaceId: cfg.workspaceId, agentId: cfg.agentId } : null,
          agentJson: hasAgent,
          contractMd: hasContract,
        },
        null,
        2,
      ),
    )
    return
  }

  const row = (k, v) => console.log(`  ${(k + ":").padEnd(12)} ${v}`)
  console.log("figs status")
  row(
    "logged in",
    loggedIn
      ? `yes (${list.length} workspace${list.length === 1 ? "" : "s"})`
      : unreachable
        ? `can't reach ${endpoint}`
        : token
          ? "token invalid — run `figs login`"
          : "no — run `figs login`",
  )
  if (loggedIn) {
    row(
      "account",
      account?.email
        ? `${account.email}${account.name ? ` (${account.name})` : ""}`
        : "—",
    )
  }
  row(
    "workspace",
    cfg?.workspaceId
      ? cfg.workspaceId
      : "not initialized — run `figs init --workspace <id>`",
  )
  row("agent.json", hasAgent ? "present (identity)" : "missing — author .figs/agent.json")
  row(
    "contract",
    hasContract
      ? "present (activity) — follow it"
      : "none yet — Activity is optional, agree it with your user",
  )
  row("endpoint", endpoint)
  row("cli", VERSION)
}

/**
 * List the user's workspaces (read-only). Creating a workspace is a human,
 * web-side action — the agent only ever joins one it was pointed at. Surfaces
 * the slug, which is what `figs init --workspace <slug>` takes.
 */
async function workspaces() {
  const { workspaces: list = [] } = await api("GET", "/api/workspaces")
  if (JSON_OUT) return void console.log(JSON.stringify(list, null, 2))
  if (list.length === 0) {
    console.log("figs: no workspaces yet — create one in the Figs web app, then re-run.")
    return
  }
  console.log(`figs: ${list.length} workspace${list.length === 1 ? "" : "s"}`)
  for (const w of list) {
    console.log(`  ${String(w.role).padEnd(6)} ${w.slug}  —  ${w.name}`)
  }
  console.log("  → figs init --workspace <slug>")
}

function isUuid(s) {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
    String(s),
  )
}

/**
 * The local `.figs/GUIDE.md` is a thin orientation breadcrumb (safe to
 * regenerate) — the full, always-current guide + schema is served at
 * `${endpoint}/llms.txt`, and the agent's own standing agreement lives in the
 * precious, agent-authored `.figs/CONTRACT.md` (which `init` never touches).
 */
function guideStub(endpoint) {
  return `<!-- Written by \`figs init\` (safe to regenerate). Orientation only — the full
     guide lives at the URL below; your own contract lives in CONTRACT.md. -->
# Figs — this folder

This repo publishes to **Figs** (your manager's read-only window into what you do).

- **Full guide + schema → ${endpoint}/llms.txt** — read this first.
- **Your contract → ./CONTRACT.md** — what you publish / hold back (you + your user author it).
- **Identity → config.json** (committed) · **charter → agent.json** (you write).
- **Stay visible:** keep the \`figs:begin\`…\`figs:end\` block in the instruction file you load every
  session (CLAUDE.md/AGENTS.md/…). It's what brought you back here — don't remove it. (Phase-1 setup; see /llms.txt.)

**Where are you?** You may be reading this at any time — don't assume you're starting fresh. Run
\`figs status\` and check \`.figs/\` before acting:
  • not set up yet → author \`.figs/agent.json\`, then \`figs doctor\` && \`figs push\` to appear (Identity).
  • CONTRACT.md present → follow it; keep publishing what it says.
  • no CONTRACT.md yet → agree with your user what work to surface (Activity) — see ${endpoint}/llms.txt.

Commit config.json + agent.json + CONTRACT.md + this file. runs.jsonl / asks.jsonl / artifacts/
are a gitignored outbox. The token is the human's job — never generate one yourself.
`
}

/**
 * A starter `agent.json` — written by `figs init` only when none exists. The
 * `<…>` values are placeholders the agent fills in by reading its own repo;
 * `figs doctor` refuses to bless a charter that still has them. `name` defaults
 * to the folder name (a sensible first guess), `id` is intentionally absent —
 * the CLI attaches the identity UUID from config.json on push.
 */
function agentJsonStub(name) {
  return (
    JSON.stringify(
      {
        name,
        role: "<one line — what you are>",
        status: "in_dev",
        mandate: "<one sentence — what you are accountable for>",
        org: { department: "<your team / department>" },
        runtime: "<what runs you, e.g. Claude Code>",
        cadence: "<on-demand · weekly · monthly · …>",
        responsibilities: ["<an area of work you own — list a few, or use steps>"],
        properties: [{ k: "<fact>", v: "<value>" }],
      },
      null,
      2,
    ) + "\n"
  )
}

/** A starter activity contract — written by `figs init` only when none exists. */
function contractStub(name) {
  return `# Activity contract — ${name} on Figs

What this agent surfaces to Figs vs. holds back. **Agree it with your user** — this is the
deliberate Activity step, not something to do mechanically. See \`.figs/GUIDE.md\` for the why.

> **Maintain:** edit when the surfacing agreement changes (a new stream, a sensitivity change).
> Keep it honest to what you actually push.

## What I surface

| Stream | Surface? | Content |
|--------|----------|---------|
| **runs** | <yes/no> | one line per run — what I did, de-identified scope, the headline result + status. |
| **artifacts** | <yes/no> | the report(s) a run produced. |
| **asks** | when real | genuine blockers / decisions / sign-offs / FYIs for my manager. 0 is a fine number. |

## What I never surface

Raw user content — ever. Plus, for this agent: <anything sensitive to its domain>. Use
**de-identified labels** (\`<scope>-01\`), never customer or system names.
`
}

/**
 * Find string values still left as `<…>` template placeholders, with their JSON
 * path. Used by `figs doctor` to block publishing a half-filled charter. Matches
 * a value that is *entirely* a placeholder (e.g. "<one line — what you are>") so
 * real content containing stray angle brackets isn't flagged.
 */
function findPlaceholders(obj) {
  const out = []
  const walk = (v, path) => {
    if (typeof v === "string") {
      if (/^<.*>$/.test(v.trim())) out.push({ path: path || "(root)", value: v })
    } else if (Array.isArray(v)) {
      v.forEach((x, i) => walk(x, `${path}[${i}]`))
    } else if (v && typeof v === "object") {
      for (const [k, x] of Object.entries(v)) walk(x, path ? `${path}.${k}` : k)
    }
  }
  walk(obj, "")
  return out
}

/**
 * Resolve which workspace this `.figs/` belongs to. `--workspace` is optional:
 *  - given a UUID  → use it as-is (no network).
 *  - given a slug  → resolve to its UUID via the API (needs auth).
 *  - omitted       → reuse the one already in config.json (idempotent re-init);
 *                    else use the user's only workspace (logged, so it's visible);
 *                    else list them and have the agent re-run with one (when
 *                    there's a real choice, the agent drives it — we never guess).
 * Returns the workspace UUID, or exits with an actionable message.
 */
async function resolveWorkspaceId(workspaceArg, endpoint) {
  if (workspaceArg) {
    if (isUuid(workspaceArg)) return workspaceArg
    if (!getToken()) {
      die("not logged in — run `figs login` first (resolving a workspace slug needs auth; or pass the workspace UUID)")
    }
    const r = await request("GET", "/api/workspaces", null, getToken())
    if (!r.ok) {
      die(`could not resolve workspace "${workspaceArg}" (${r.status}): ${r.data.error ?? r.data.raw ?? ""}`)
    }
    const list = r.data.workspaces ?? []
    const match = list.find((w) => w.slug === workspaceArg || w.id === workspaceArg)
    if (!match) die(`no workspace matching "${workspaceArg}" — run \`figs workspaces\` to see yours`)
    return match.id
  }

  // No --workspace: a re-init keeps the workspace already on file.
  const existing = readJson(join(repoDir, "config.json"), null)
  if (existing?.workspaceId) return existing.workspaceId

  // First-time init with no workspace named — use the only one, else list them.
  if (!getToken()) {
    die("which workspace? run `figs login` first so I can list them, then `figs init --workspace <slug>` (or pass a workspace UUID directly)")
  }
  const r = await request("GET", "/api/workspaces", null, getToken())
  if (!r.ok) die(`could not list workspaces (${r.status}): ${r.data.error ?? r.data.raw ?? ""}`)
  const list = r.data.workspaces ?? []
  if (list.length === 0) {
    die(`no workspaces yet — create one at ${endpoint}, then re-run \`figs init --workspace <slug>\``)
  }
  if (list.length === 1) {
    console.log(`figs: using workspace ${list[0].slug} (${list[0].name})`)
    return list[0].id
  }
  console.log("figs: which workspace? re-run init with one of these:")
  for (const w of list) console.log(`        figs init --workspace ${w.slug}   (${w.name})`)
  process.exit(1)
}

async function init() {
  const endpoint = (flag("--endpoint") || resolveEndpoint()).replace(/\/+$/, "")
  const workspaceId = await resolveWorkspaceId(flag("--workspace"), endpoint)

  // config.json (identity + destination) is always (re)written — it's the one
  // file the CLI owns. A re-init reuses the existing identity UUID so every
  // runner of this repo pushes to the same agent.
  const existing = readJson(join(repoDir, "config.json"), null)
  const agentId = existing?.agentId || randomUUID()
  mkdirSync(repoDir, { recursive: true })
  writeFileSync(
    join(repoDir, "config.json"),
    JSON.stringify({ endpoint, workspaceId, agentId }, null, 2) + "\n",
  )

  // Everything else is scaffolded create-if-missing — `figs init` gives a fresh
  // repo a complete, ready-to-fill `.figs/`, and never clobbers an agent's
  // authored charter/contract/guide or its activity outbox.
  const created = []
  const ensure = (rel, contents) => {
    const p = join(repoDir, rel)
    if (existsSync(p)) return false
    writeFileSync(p, contents)
    created.push(rel)
    return true
  }
  ensure(
    ".gitignore",
    [
      "# Figs — commit config.json + agent.json + CONTRACT.md + GUIDE.md.",
      "# Activity is a transient outbox: emitted per run, aggregated remotely.",
      "runs.jsonl",
      "asks.jsonl",
      "artifacts/",
      "credentials.json",
      "",
    ].join("\n"),
  )
  ensure("GUIDE.md", guideStub(endpoint))
  const name = basename(process.cwd())
  const charterCreated = ensure("agent.json", agentJsonStub(name))
  ensure("CONTRACT.md", contractStub(name))
  ensure("runs.jsonl", "")
  ensure("asks.jsonl", "")
  mkdirSync(join(repoDir, "artifacts"), { recursive: true })

  console.log(
    `figs: ✓ .figs/ ready — config.json written (agentId ${agentId}, workspace ${workspaceId})`,
  )
  if (created.length) console.log(`        scaffolded: ${created.join(", ")}`)
  if (charterCreated) {
    console.log(
      "        Phase 1: fill in .figs/agent.json — it's a template; replace the <…> placeholders",
    )
    console.log(
      "        (`figs doctor` flags any you miss), then `figs doctor` && `figs push` to appear.",
    )
  } else {
    console.log(
      "        Your charter (.figs/agent.json) is already here — `figs doctor` && `figs push` to publish.",
    )
  }
  console.log(
    "        Anchor Figs in the file you load every session (CLAUDE.md/AGENTS.md/…): paste the",
  )
  console.log(`        figs:begin block from ${endpoint}/llms.txt, or future sessions forget Figs.`)
  console.log(
    "        Commit config.json + agent.json + CONTRACT.md + GUIDE.md; never commit credentials.json.",
  )
  console.log(`        Full guide: ${endpoint}/llms.txt`)
}

// ====================== the writing verbs ===================================
// report / ask / resolve — sugar over the same files (hand-writing stays
// first-class). The agent supplies content; the CLI stamps id + real-clock ts,
// validates with teaching errors, copies attachments, then invokes the same
// push as `figs push`.
//
// NOTE — no session auto-capture (removed in 0.5.0). The CLI used to infer a
// `session` trace (runtime/model/tokens) from "the newest transcript on this
// machine"; in nested/headless runs that stamped the WRONG runtime+model — a
// fabricated audit line (e.g. gpt-5.5 on a Claude Code run). A trace must be
// true or absent, never false, so inference is gone. The spec's optional
// `session` block remains legal for integrations that can copy provable values
// from the runtime's own records at work-time.

function requireFigs() {
  if (!existsSync(repoDir)) die("no .figs/ here — run `figs init` first")
  const config = readJson(join(repoDir, "config.json"), {})
  if (!config.workspaceId || !config.agentId) {
    die("config missing workspaceId/agentId — run `figs init`")
  }
}
function appendJsonl(name, obj) {
  appendFileSync(join(repoDir, name), JSON.stringify(obj) + "\n")
}
/** Copy attachments into artifacts/ — ext + size checks; immutable once there. */
function attachFiles(paths) {
  const names = []
  for (const p of paths) {
    if (!existsSync(p)) die(`--attach: no such file: ${p}`)
    const ext = extname(p).toLowerCase()
    if (!ARTIFACT_EXTS.has(ext)) {
      die(`--attach: unsupported type "${ext || p}" — supported: ${[...ARTIFACT_EXTS].join(" ")}`)
    }
    const bytes = readFileSync(p)
    if (bytes.length > ARTIFACT_MAX) {
      die(`--attach: ${basename(p)} is ${(bytes.length / 1048576).toFixed(1)} MB — over the 3 MB cap; compress or split it`)
    }
    const name = basename(p)
    const dest = join(repoDir, "artifacts", name)
    if (existsSync(dest) && !readFileSync(dest).equals(bytes)) {
      die(
        `--attach: artifacts/${name} already exists with different content — artifacts are immutable once published; use a new name (e.g. ${name.slice(0, -ext.length)}-v2${ext}) and reference that`,
      )
    }
    mkdirSync(join(repoDir, "artifacts"), { recursive: true })
    writeFileSync(dest, bytes)
    names.push(name)
  }
  return names
}

// A `$` eaten by the caller's shell (double-quoted "$4,474.63" → ",474.63")
// leaves a signature legit prose essentially never has: an orphaned thousands
// group or a bare ".00" cents tail. Best-effort tripwire — warn and teach,
// never block (the heuristic can't be certain, and records fold by id, so a
// corrected re-run heals the row). "$1K" → "K" leaves no signature; that case
// is why every emitted template teaches single-quoted prose in the first place.
function warnEatenDollar(...texts) {
  // regex lives inside the function: the CLI dispatches commands during module
  // evaluation, so a top-level const here would still be in its TDZ when called
  const eaten = /(^|[\s([{])(,\d{3}\b|\.00\b)/
  if (texts.flat().filter(Boolean).some((t) => eaten.test(String(t)))) {
    console.warn(
      "figs: ! a value looks like your shell ate a `$` (\"$4,474.63\" in double quotes becomes \",474.63\") — single-quote prose args ('…') and re-run; the same id folds the fix onto the record",
    )
  }
}

// ---------- the inbox (the DOWN direction — a pure read) ---------------------

/** Relative time for inbox lines — rough on purpose. */
function agoStr(iso) {
  const mins = Math.max(0, Math.round((Date.now() - new Date(iso).getTime()) / 60000))
  if (mins < 60) return `${mins}m ago`
  if (mins < 60 * 48) return `${Math.round(mins / 60)}h ago`
  return `${Math.round(mins / 1440)}d ago`
}

/** Fetch this agent's inbox; null on any failure when `soft` (auto-cite path). */
async function fetchInbox({ soft = false } = {}) {
  const config = readJson(join(repoDir, "config.json"), {})
  if (!config.agentId) {
    if (soft) return null
    die("config missing agentId — run `figs init`")
  }
  const r = await request("GET", `/api/inbox?agent=${config.agentId}`)
  if (!r.ok) {
    if (soft) return null
    die(`inbox failed (${r.status || "network"}): ${r.data.error ?? r.data.raw ?? ""}`)
  }
  return r.data
}

/** One human event, verbatim — answers are instructions; never paraphrase them. */
function eventLine(e) {
  const head =
    e.kind === "verdict"
      ? `${e.verdict.replace(/_/g, " ")} by ${e.byName} (${e.asRole})`
      : `answered by ${e.byName} (${e.asRole})`
  const body = [e.chosen ? `→ "${e.chosen}"` : null, e.text ? `"${e.text}"` : null]
    .filter(Boolean)
    .join(" · ")
  return `${head} · ${agoStr(e.createdAt)}${body ? `\n      ${body}` : ""}`
}

/** The type×state matrix → the exact next command. The stranger never needs
 *  to know the state machine — the protocol tells them their move. */
function nextMove(a) {
  if (a.status === "rejected") {
    return `a human declined this — acknowledge it: figs resolve ${a.id} --rejected`
  }
  const last = a.events[a.events.length - 1]
  if (!last) return "waiting on your human — nothing for you to do"
  if (last.kind === "verdict" && last.verdict === "approved") {
    // A qualified verdict carries the chosen answer path — cite it in the close.
    const chosen = last.chosen ? ` --chosen '${last.chosen}'` : ""
    return (
      `approved — verify any prerequisites in the ask, then fork on what it unlocked:` +
      `\n      nothing left to do → figs resolve ${a.id}${chosen}` +
      `\n      real work → do the job, figs report it under its own --id, then figs resolve ${a.id}${chosen} --note 'job <id>'`
    )
  }
  if (last.kind === "verdict" && last.verdict === "changes_requested") {
    return `revise, then re-raise on the same id: figs ask ${a.type} --id ${a.id} --title '…' …`
  }
  if (last.chosen) {
    // Pre-fill the cited option verbatim — the note is substance for --note, never for --chosen.
    const note = last.text ? ` --note '…'` : ""
    return `act on the answer (real work → figs report it under its own --id), then: figs resolve ${a.id} --chosen '${last.chosen}'${note}`
  }
  return `act on the answer (real work → figs report it under its own --id), then: figs resolve ${a.id} --note '…'`
}

/** Restore an ask's refs into artifacts/ — hash-verified; never clobbers. */
async function fetchRefs(config, refs) {
  for (const ref of refs ?? []) {
    if (!ref.artifact) continue
    const name = ref.artifact
    let res
    try {
      res = await fetchT(
        `${resolveEndpoint()}/api/artifacts/raw?agent=${config.agentId}&name=${encodeURIComponent(name)}`,
        { headers: { "x-figs-token": getToken() } },
      )
    } catch (e) {
      console.warn(`figs: ! couldn't fetch artifacts/${name} (${netReason(e)})`)
      continue
    }
    if (!res.ok) {
      console.warn(`figs: ! couldn't fetch artifacts/${name} (${res.status})`)
      continue
    }
    const bytes = Buffer.from(await res.arrayBuffer())
    const want = res.headers.get("x-figs-sha256")
    if (want && createHash("sha256").update(bytes).digest("hex") !== want) {
      console.warn(`figs: ! artifacts/${name}: bytes didn't match the server's hash — skipped`)
      continue
    }
    const dest = join(repoDir, "artifacts", name)
    if (existsSync(dest)) {
      if (readFileSync(dest).equals(bytes)) {
        console.log(`figs:   ✓ artifacts/${name} (already present)`)
      } else {
        console.warn(
          `figs: ! artifacts/${name} exists locally with different content — left untouched (the published copy stays one fetch away)`,
        )
      }
      continue
    }
    mkdirSync(join(repoDir, "artifacts"), { recursive: true })
    writeFileSync(dest, bytes)
    console.log(`figs:   ✓ artifacts/${name} (fetched, hash ok)`)
  }
}

/**
 * `figs inbox` — session start. Bare: every ask with thread activity + the
 * next command for each. With an id: the zero-context handoff package (the
 * ask, the whole thread verbatim, refs restored to disk). Pure read — writes
 * nothing to the outbox; closing happens via resolve.
 */
async function inboxCmd() {
  requireFigs()
  const config = readJson(join(repoDir, "config.json"), {})
  const data = await fetchInbox()
  const items = data.asks ?? []
  const askId = positional()

  if (hasFlag("--json") && !askId) {
    console.log(JSON.stringify(data, null, 2))
    return
  }

  if (askId) {
    const a = items.find((x) => x.id === askId)
    if (!a) {
      die(
        `ask "${askId}" isn't in your inbox (open asks + unacknowledged rejections only — closed history lives in the app)`,
      )
    }
    console.log(`figs: ${a.title}`)
    console.log(`      ${a.type} · ${a.status}${a.to ? ` · for the ${a.to}` : ""} · raised ${agoStr(a.ts)}`)
    if (a.found) console.log(`\n  What it found:\n      ${a.found}`)
    if (a.need) console.log(`\n  What it needs:\n      ${a.need}`)
    if (a.options?.length) {
      console.log(`\n  Options (answers cite these verbatim):`)
      for (const o of a.options) console.log(`      · ${o}`)
    }
    if (a.details?.length) {
      console.log(`\n  Details:`)
      for (const d of a.details) console.log(`      ${d.l}: ${d.v}`)
    }
    if (a.events.length) {
      console.log(`\n  THE THREAD (your humans' words, verbatim):`)
      for (const e of a.events) console.log(`    · ${eventLine(e)}`)
    } else {
      console.log(`\n  No answer yet.`)
    }
    if (a.refs?.length) {
      console.log(`\n  Attached artifacts (restoring to .figs/artifacts/):`)
      await fetchRefs(config, a.refs)
    }
    console.log(`\n  → next: ${nextMove(a)}`)
    return
  }

  if (data.truncated) {
    console.warn(`figs: ! showing the first ${items.length} — more exist (close some asks)`)
  }
  const jobs = data.jobs ?? []
  if (items.length === 0 && jobs.length === 0) {
    console.log("figs: ✓ inbox empty — no open asks, no unfinished jobs, nothing needs you")
    return
  }
  const rejected = items.filter((a) => a.status === "rejected")
  const answered = items.filter((a) => a.status === "open" && a.events.length > 0)
  const quiet = items.filter((a) => a.status === "open" && a.events.length === 0)
  console.log(
    `figs: inbox — ${answered.length} answered · ${rejected.length} rejected to acknowledge · ${quiet.length} waiting on your human` +
      (jobs.length ? ` · ${jobs.length} job${jobs.length === 1 ? "" : "s"} in flight` : ""),
  )
  const printItem = (a) => {
    const last = a.events[a.events.length - 1]
    console.log(`\n  ${a.id} · ${a.type} — ${a.title}`)
    if (last) console.log(`    ${eventLine(last)}`)
    console.log(`    → ${nextMove(a)}${a.events.length > 1 ? `   (full thread: figs inbox ${a.id})` : ""}`)
  }
  for (const a of [...rejected, ...answered]) printItem(a)
  if (quiet.length) {
    console.log(`\n  Waiting on your human (nothing for you to do):`)
    for (const a of quiet) console.log(`    · ${a.id} · ${a.type} — ${a.title} (raised ${agoStr(a.ts)})`)
  }
  if (jobs.length) {
    console.log(`\n  Unfinished jobs — in flight (your past self's work; finish or settle):`)
    for (const j of jobs) {
      console.log(
        `    · ${j.id}${j.result ? ` — ${j.result}` : ""} (last update ${agoStr(j.updatedAt ?? j.ts)})`,
      )
      console.log(
        `      → continue it (\`figs checkpoint --id ${j.id}\` as you go); \`figs report --id ${j.id}\` settles it`,
      )
    }
  }
}

// ---------- the resolution fold (`resolve` — the one closing verb) ----------
/**
 * Build the closing fold line. Best-effort, the verified path: fetches this
 * agent's inbox and, when the ask has human events, cites the one acted on —
 * `via: "figs"` + `resolution.answer: <event-id>` (+ `by` from the event) —
 * attribution by mechanism, not testimony. An ask found on the server but
 * missing locally is appended first (its own bytes coming home), so the fold
 * lands on a complete record. Offline or any failure → today's self-reported
 * `via: "human"` path, unchanged.
 */
async function buildResolution(askId, { chosen, by, note, withdrawn, rejected }) {
  if (withdrawn && rejected) {
    die("--withdrawn and --rejected are different closes: withdrawn = YOU retracted the ask; rejected = a HUMAN declined it. Pick the one that's true.")
  }
  if ((withdrawn || rejected) && chosen) {
    die(`--chosen marks the need as met — it can't combine with ${withdrawn ? "--withdrawn" : "--rejected"} (use --note for the account)`)
  }
  const warnings = []
  let ask = foldById(readJsonl("asks.jsonl")).find((a) => a.id === askId)

  // The verified path (soft — never blocks a close).
  let serverAsk = null
  if (getToken()) {
    const inbox = await fetchInbox({ soft: true })
    serverAsk = inbox?.asks?.find((a) => a.id === askId) ?? null
  }
  if (!ask && serverAsk) {
    // Its own bytes coming home: append the record so the fold has something
    // local to land on (the cross-machine close, solved inside the verb).
    const record = { ...serverAsk }
    delete record.events
    delete record.updatedAt
    if (record.resolution == null) delete record.resolution
    appendJsonl("asks.jsonl", record)
    warnings.push(`fetched "${askId}" from Figs (raised elsewhere) — recorded locally before closing`)
    ask = record
  } else if (!ask) {
    warnings.push(
      `ask "${askId}" isn't in the local asks.jsonl (raised on another machine, or pruned) — recording the close anyway; the server folds it onto the full record`,
    )
  }

  const options = ask?.options ?? serverAsk?.options ?? []
  if (chosen && options.length && !options.includes(chosen)) {
    const norm = (s) => s.toLowerCase().replace(/[^a-z0-9]/g, "")
    const near = options.find((o) => norm(o) === norm(chosen))
    if (near) die(`--chosen must quote the option verbatim — did you mean "${near}"?`)
    die(
      `--chosen "${chosen}" doesn't match any of the ask's options:\n` +
        options.map((o) => `    · ${o}`).join("\n") +
        "\n  (quote one verbatim, or use --note for a free-text account)",
    )
  }

  const resolution = {}
  if (chosen) resolution.chosen = chosen
  if (by) resolution.by = by
  if (note) resolution.note = note
  // `via` says where the unblock came from; out-of-band human answers are
  // "human". A rejection is inherently a human's call; otherwise set it only
  // when there's evidence of one (a chosen/by), never on withdrawn (nobody
  // acted — that's the point).
  if (rejected || (!withdrawn && (chosen || by))) resolution.via = "human"

  // Cite the event acted on, when one exists: prefer the latest answer whose
  // chosen matches, else the latest event (e.g. the approval, the rejection).
  const events = serverAsk?.events ?? []
  if (!withdrawn && events.length) {
    // Any human event can carry the chosen path — an answer, or a qualified
    // verdict (verdict + chosen together). Match on the text, not the kind.
    const match = chosen ? [...events].reverse().find((e) => e.chosen === chosen) : null
    const cited = match ?? events[events.length - 1]
    resolution.via = "figs"
    resolution.answer = cited.id
    if (!by && cited.byName) resolution.by = cited.byName
  }

  // The close's own clock — machine-stamped, never typed (same posture as the
  // record `ts`). It lives INSIDE resolution so the fold can't collide with
  // the record's raise `ts` (folds are field-level merges); the reader stamps
  // its own receipt (`closedAt`) at ingest — two clocks, claim vs receipt.
  resolution.ts = nowIso()

  warnEatenDollar(resolution.chosen, resolution.note)
  const line = {
    id: askId,
    status: withdrawn ? "withdrawn" : rejected ? "rejected" : "resolved",
    resolution,
  }
  return { line, warnings }
}

/** The verbs' shared final step — same transport as `figs push`. */
async function autoPush() {
  if (hasFlag("--no-push")) {
    console.log("figs:   saved locally (--no-push) — `figs push` publishes it")
    return
  }
  if (!(await doPush())) {
    console.warn("figs: ! saved locally — the push failed (see above); fix and run `figs push`")
    process.exitCode = 1
  }
}

async function reportCmd() {
  requireFigs()
  const result = flag("--result")
  if (!result) {
    die("report needs --result '<one-line outcome>' — e.g. figs report --result '88% matched · 31 flagged'")
  }
  // state is verb-stamped, never typed: report settles the job (checkpoint
  // marks it in-flight). The settling fold overrides any earlier checkpoint.
  const run = { id: flag("--id") || genId("r"), ts: nowIso(), result, state: "settled" }
  const unit = flag("--unit")
  if (unit) run.unit = unit
  const period = flag("--period")
  if (period) run.period = period
  const status = flag("--status")
  if (status) run.status = status
  const trigger = flag("--trigger")
  if (trigger) run.session = { trigger }
  const attached = attachFiles(flagAll("--attach"))
  if (attached.length === 1) run.artifact = attached[0]
  else if (attached.length > 1) run.artifacts = attached
  warnEatenDollar(run.result)
  const issues = validateRun(run)
  if (issues.length) die(`not written:\n  ${issues.join("\n  ")}`)
  appendJsonl("runs.jsonl", run)
  console.log(`figs: ✓ run recorded — ${JSON.stringify(run)}`)
  await autoPush()
}

/**
 * `figs checkpoint` — save a job's progress so it survives this sitting. The
 * first checkpoint on an id OPENS the job (state: in-flight); a crash mid-job
 * then leaves a visible, recoverable stub the next session finds in
 * `figs inbox`, instead of nothing. Same fold-by-id write as report — only
 * the stamped state differs; `figs report` settles the id.
 */
async function checkpointCmd() {
  requireFigs()
  const id = flag("--id")
  if (!id) {
    die("checkpoint needs --id '<job-id>' — the stable job id the next session will look for (e.g. recon-acme-2026-11)")
  }
  const note = flag("--note")
  if (!note) {
    die(`checkpoint needs --note '<where the job stands>' — e.g. figs checkpoint --id ${id} --note 'Statements pulled — matching now'`)
  }
  // Before the append, so "new" means new-to-this-outbox (the teaching line).
  const isNew = !foldById(readJsonl("runs.jsonl")).some((r) => r.id === id)
  const run = { id, ts: nowIso(), result: note, state: "in-flight" }
  const unit = flag("--unit")
  if (unit) run.unit = unit
  const period = flag("--period")
  if (period) run.period = period
  const status = flag("--status")
  if (status) run.status = status
  const trigger = flag("--trigger")
  if (trigger) run.session = { trigger }
  const attached = attachFiles(flagAll("--attach"))
  if (attached.length === 1) run.artifact = attached[0]
  else if (attached.length > 1) run.artifacts = attached
  warnEatenDollar(run.result)
  const issues = validateRun(run)
  if (issues.length) die(`not written:\n  ${issues.join("\n  ")}`)
  appendJsonl("runs.jsonl", run)
  console.log(`figs: ✓ checkpoint recorded — ${JSON.stringify(run)}`)
  if (isNew) {
    console.log(
      `figs:   new job opened: ${id} (in flight) — checkpoint as you go; \`figs report --id ${id}\` settles it`,
    )
  }
  await autoPush()
  // A checkpoint exists to survive a crash — local-only protects nothing.
  // autoPush already said "saved locally"; for THIS verb that reads like
  // success, so say what it actually means.
  if (process.exitCode === 1) {
    console.warn(
      `figs: ! this checkpoint is NOT protecting the job yet — nothing reached the server. Run \`figs push\` before continuing the work.`,
    )
  }
}

async function askCmd() {
  requireFigs()
  let base = {}
  if (hasFlag("--stdin")) {
    let raw = ""
    try {
      raw = readFileSync(0, "utf8")
    } catch {
      /* no stdin */
    }
    if (!raw.trim()) die("--stdin given but nothing arrived on stdin — pipe a JSON object")
    try {
      base = JSON.parse(raw)
    } catch (e) {
      die(`--stdin: invalid JSON: ${e.message}`)
    }
    if (!base || typeof base !== "object" || Array.isArray(base)) {
      die("--stdin must be a single JSON object (one ask)")
    }
  }
  const type = positional() ?? base.type
  if (!type) die(`ask needs a type: figs ask <${ASK_TYPES.join("|")}> --title '…'`)
  const ask = { ...base, id: flag("--id") ?? base.id ?? genId("ask"), ts: nowIso(), type }
  if (!ask.status) ask.status = "open"
  const title = flag("--title") ?? base.title
  if (!title) die("ask needs --title '<the ask, in one line>'")
  ask.title = title
  for (const [f, k] of [["--need", "need"], ["--found", "found"], ["--unit", "unit"], ["--to", "to"]]) {
    const v = flag(f)
    if (v) ask[k] = v
  }
  const options = flagAll("--option")
  if (options.length) ask.options = options
  for (const o of ask.options ?? []) {
    if (o.length > 80) {
      console.warn(
        `figs: ! option "${o.slice(0, 40)}…" is long — options should be short, stable, quotable (an answer cites one verbatim)`,
      )
    }
  }
  const onApprove = flagAll("--on-approve")
  if (onApprove.length) ask.onApprove = onApprove
  if (ask.onApprove?.length && ask.type !== "sign-off") {
    die(
      `--on-approve is the approval contract — sign-off only. A ${ask.type} has no approval; the chosen option carries the next step (put it in the --option text)`,
    )
  }
  const details = flagAll("--detail").map((d) => {
    const i = d.indexOf("=")
    if (i < 1) die(`--detail must be "Label=Value", got "${d}"`)
    return { l: d.slice(0, i), v: d.slice(i + 1) }
  })
  if (details.length) ask.details = [...(base.details ?? []), ...details]
  const runRef = flag("--run")
  if (runRef === "last") {
    // Deliberately unsupported: concurrent sessions of the same agent report
    // runs in parallel — "the latest run" may be someone else's. Explicit only.
    die('--run takes the explicit run id (no "last" — another session may have reported since); `figs report` prints the id of what it wrote')
  }
  if (runRef) ask.run = runRef
  const attached = attachFiles(flagAll("--attach"))
  if (attached.length) {
    ask.refs = [...(base.refs ?? []), ...attached.map((n) => ({ label: n, artifact: n }))]
  }
  if (ask.type === "sign-off" && !ask.refs?.length) {
    console.warn(
      "figs: ! tip: a sign-off reviews best with attachments — the exact content to approve, plus a brief (what to do once approved + what it requires). Add --attach <file>",
    )
  }
  if (ask.type === "sign-off" && !ask.onApprove?.length) {
    console.warn(
      "figs: ! tip: state what approval sets in motion — --on-approve '<step>' (repeatable, ordered); an approver shouldn't have to guess what approve causes",
    )
  }
  warnEatenDollar(
    ask.title,
    ask.found,
    ask.need,
    ask.options ?? [],
    ask.onApprove ?? [],
    (ask.details ?? []).flatMap((d) => [d.l, d.v]),
  )
  const issues = validateAsk(ask)
  if (issues.length) die(`not written:\n  ${issues.join("\n  ")}`)
  appendJsonl("asks.jsonl", ask)
  console.log(`figs: ✓ ask raised — ${JSON.stringify(ask)}`)
  if (!ask.to) {
    console.log("figs:   tip: address asks with --to manager|builder so they route to the right person")
  }
  await autoPush()
  console.log(
    "figs:   your human answers in the app — start your next session with `figs inbox` to read it",
  )
}

async function resolveCmd() {
  requireFigs()
  const askId = positional()
  if (!askId) die("resolve needs the ask id: figs resolve <ask-id> [--chosen …] [--withdrawn]")
  const { line, warnings } = await buildResolution(askId, {
    chosen: flag("--chosen"),
    by: flag("--by"),
    note: flag("--note"),
    withdrawn: hasFlag("--withdrawn"),
    rejected: hasFlag("--rejected"),
  })
  for (const w of warnings) console.warn(`figs: ! ${w}`)
  appendJsonl("asks.jsonl", line)
  console.log(`figs: ✓ ask ${askId} ${line.status} — ${JSON.stringify(line)}`)
  await autoPush()
}

/** Validate the local .figs/ payload against the spec — no write, no push. */
async function doctor() {
  // Local checks first (no token/network needed) — fail fast and offline.
  if (!existsSync(repoDir)) die("no .figs/ here — run `figs init` first")
  const config = readJson(join(repoDir, "config.json"), {})
  if (!config.workspaceId || !config.agentId) {
    die("config missing workspaceId/agentId — run `figs init`")
  }
  const agentJson = readJson(join(repoDir, "agent.json"), null)
  if (!agentJson) die("missing .figs/agent.json — author it first (see .figs/GUIDE.md)")

  // Refuse to bless a charter that still has `<…>` template placeholders — `figs
  // init` scaffolds them, and pushing them would publish "<one line — what you
  // are>" to the org chart. This is the "not ready to push" signal.
  const placeholders = findPlaceholders(agentJson)
  if (placeholders.length) {
    console.log("figs: ✗ .figs/agent.json still has template placeholders — fill these in before pushing:")
    for (const p of placeholders) console.log(`  ${p.path}: ${p.value}`)
    console.log("  (replace the <…> values by reading your own repo, then re-run `figs doctor`)")
    process.exit(1)
  }

  // Same local checks the write-path runs — catches hand-authored mistakes
  // offline, before the server round-trip.
  const localIssues = validateOutbox(
    foldById(readJsonl("runs.jsonl")),
    foldById(readJsonl("asks.jsonl")),
  )
  if (localIssues.length) {
    console.log("figs: ✗ local validation issues:")
    for (const i of localIssues) console.log(`  ${i}`)
    process.exit(1)
  }

  if (!getToken()) die("not logged in — run `figs login`")
  const r = await api("POST", "/api/validate", {
    workspaceId: config.workspaceId,
    agent: { ...agentJson, id: config.agentId },
    runs: foldById(readJsonl("runs.jsonl")),
    asks: foldById(readJsonl("asks.jsonl")),
  })
  if (r.ok) {
    console.log("figs: ✓ .figs/ is valid — ready to push")
    return
  }
  if (JSON_OUT) {
    console.log(JSON.stringify(r.issues, null, 2))
  } else {
    console.log("figs: ✗ validation issues:")
    for (const i of r.issues) {
      console.log(`  ${i.path || "(root)"}: ${i.message}`)
      // The server quotes the canonical shape for the field you got wrong —
      // show it so you don't have to re-read the guide to fix it.
      if (i.expected) console.log(`      expected e.g. ${i.expected}`)
    }
    console.log(`  (full shapes + a valid example: ${resolveEndpoint()}/llms.txt)`)
  }
  process.exit(1)
}

/** `figs push` — the bare transport; exits non-zero on any failure. */
async function push() {
  if (!(await doPush())) process.exit(1)
}

/**
 * The one transport: spine → /api/ingest, artifacts → /api/artifacts/upload.
 * `figs push` is a thin wrapper; the writing verbs call this after their local
 * append (auto-push IS push — one transport, many entry points). Runs the same
 * local checks as `figs doctor` first, so a malformed hand-written line never
 * reaches the server as a confusing 4xx. Prints its own errors and returns
 * false on failure — callers decide whether that's fatal.
 */
async function doPush() {
  const fail = (msg) => {
    console.error(`figs: ✗ push: ${msg}`)
    return false
  }
  const token = getToken()
  if (!token) return fail("not logged in — run `figs login` (or set FIGS_TOKEN)")
  await checkVersion({ hardFail: true })
  if (!existsSync(repoDir)) return fail("no .figs/ here — run `figs init` first")
  const config = readJson(join(repoDir, "config.json"), {})
  if (!config.workspaceId || !config.agentId) {
    return fail("config missing workspaceId/agentId — run `figs init`")
  }
  const endpoint =
    process.env.FIGS_ENDPOINT || config.endpoint || DEFAULT_ENDPOINT

  const agentJson = readJson(join(repoDir, "agent.json"), null)
  if (!agentJson) return fail("missing .figs/agent.json")
  const agent = { ...agentJson, id: config.agentId }
  const runs = foldById(readJsonl("runs.jsonl"))
  const asks = foldById(readJsonl("asks.jsonl"))

  // Local pre-flight — fail fast, offline, with teaching errors.
  const placeholders = findPlaceholders(agentJson)
  if (placeholders.length) {
    return fail(
      `agent.json still has template placeholders (${placeholders.map((p) => p.path).join(", ")}) — fill them in; \`figs doctor\` lists them`,
    )
  }
  const issues = validateOutbox(runs, asks)
  if (issues.length) return fail(`local validation failed:\n  ${issues.join("\n  ")}`)

  const base = endpoint.replace(/\/+$/, "")
  let res
  try {
    res = await fetchT(`${base}/api/ingest`, {
      method: "POST",
      headers: { "content-type": "application/json", "x-figs-token": token },
      body: JSON.stringify({ workspaceId: config.workspaceId, agent, runs, asks }),
    })
  } catch (e) {
    return fail(`cannot reach ${base} (${netReason(e)})`)
  }
  const text = await res.text()
  if (!res.ok) return fail(`server rejected it (${res.status}): ${text}`)
  console.log(
    `figs: ✓ pushed ${agent.name ?? agent.id} — ${runs.length} runs, ${asks.length} asks`,
  )
  // The wow-moment link — relay this to your human so they can see the agent.
  console.log(`       view at ${base}/w/${config.workspaceId}`)

  return pushArtifacts(base, token, config, runs, asks)
}

/**
 * Upload the files referenced by runs (run.artifact) and ask refs (refs[].artifact).
 * The spine ingest is JSON-only; artifacts go to a separate endpoint that stores
 * them content-addressed (an unchanged file is skipped server-side). Content is
 * sent base64-encoded so any type — html, markdown, text, json, images — survives.
 * A **server rejection** (auth/size/etc.) is fatal: it prints ✗ and exits non-zero
 * so the agent never believes a report published when it didn't (esp. the ~3 MB
 * cap → 413). A **missing local file** is only a warning — that's the agent
 * referencing an artifact it didn't actually produce, not a publish failure.
 */
async function pushArtifacts(base, token, config, runs, asks) {
  const refNames = (asks ?? []).flatMap((a) =>
    (a.refs ?? []).map((r) => r.artifact),
  )
  const runNames = runs.flatMap((r) => [r.artifact, ...(r.artifacts ?? [])])
  const names = [...new Set([...runNames, ...refNames].filter(Boolean))]
  if (names.length === 0) return true

  let uploaded = 0
  let unchanged = 0
  let missing = 0
  let failed = 0
  for (const name of names) {
    const p = join(repoDir, "artifacts", name)
    if (!existsSync(p)) {
      console.warn(`figs: ! artifact missing, skipped: artifacts/${name}`)
      missing++
      continue
    }
    const content = readFileSync(p).toString("base64")
    let res
    try {
      res = await fetchT(`${base}/api/artifacts/upload`, {
        method: "POST",
        headers: { "content-type": "application/json", "x-figs-token": token },
        body: JSON.stringify({
          workspaceId: config.workspaceId,
          agentId: config.agentId,
          name,
          content,
        }),
      })
    } catch (e) {
      console.error(`figs: ✗ artifact upload failed ${name}: ${netReason(e)}`)
      failed++
      continue
    }
    if (!res.ok) {
      const t = await res.text().catch(() => "")
      const hint =
        res.status === 413 ? " — too large (>3 MB); compress or split it" : ""
      console.error(
        `figs: ✗ artifact upload failed (${res.status}) ${name}${hint}${t ? `: ${t}` : ""}`,
      )
      failed++
      continue
    }
    const body = await res.json().catch(() => ({}))
    if (body.unchanged) unchanged++
    else uploaded++
  }
  console.log(
    `figs: ${failed ? "✗" : "✓"} artifacts — ${uploaded} uploaded, ${unchanged} unchanged` +
      (missing ? `, ${missing} missing` : "") +
      (failed ? `, ${failed} failed` : ""),
  )
  // The spine already landed; a false return lets the caller exit non-zero so
  // an agent's run loop can catch that an artifact the manager needs to read
  // did not publish.
  return failed === 0
}

function readJsonl(name) {
  const p = join(repoDir, name)
  if (!existsSync(p)) return []
  const out = []
  readFileSync(p, "utf8")
    .split("\n")
    .forEach((line, i) => {
      const s = line.trim()
      if (!s) return
      try {
        out.push(JSON.parse(s))
      } catch {
        die(`malformed JSON in .figs/${name} line ${i + 1}: ${s.slice(0, 80)}`)
      }
    })
  return out
}

/** Fold append-only records by id — latest line wins. */
function foldById(rows) {
  const m = new Map()
  for (const r of rows) m.set(r.id, { ...(m.get(r.id) ?? {}), ...r })
  return [...m.values()]
}
