#!/usr/bin/env node
/**
 * `figs` — the agent-side CLI (v1, zero-dependency).
 *
 *   figs status                         show login / workspace / agent state    [--json]
 *   figs login                          opens browser to approve (device flow) — agent never sees the token
 *   figs login <token>                  fallback: save a token you pasted (~/.figs/credentials.json)
 *   figs logout                         remove the locally-saved token (~/.figs/credentials.json)
 *   figs workspaces                     list the user's workspaces               [--json]
 *   figs init --workspace <slug-or-id> [--endpoint <url>]
 *                                         create .figs/config.json + GUIDE.md (generates a stable agent id)
 *   figs doctor                         validate .figs/ against the contract before pushing
 *   figs push                           one-way push the .figs/ spine to the ingest endpoint
 *   figs version                        print the CLI version (and check for updates)
 *   figs help [<command>]               usage; `-h`/`--help` on any command, `-v` for version
 *
 * Designed to be driven by an agent: non-interactive, clear output, `--json`
 * on read commands, `-h`/`--help`/`help` everywhere, and errors that say what to
 * do next. Bare `figs` prints help; unknown commands AND unknown flags exit
 * non-zero (no silent no-ops). Flags accept `--name value` or `--name=value`.
 * Network calls time out (30s) instead of hanging the agent.
 *
 * Auth is the *user* (a token, configured once per machine). Identity is the
 * *agent* — a UUID generated by `init`, stored in the committed, non-secret
 * .figs/config.json ({ endpoint, workspaceId, agentId }). Run from the
 * agent's repo root, where `.figs/` lives.
 */

import {
  chmodSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import { homedir } from "node:os"
import { basename, join } from "node:path"
import { randomUUID } from "node:crypto"
import { spawn } from "node:child_process"

// Single source of truth for the version: package.json (shipped alongside this
// file in the published package). One edit keeps `figs version`, the floor
// check, and the npm package in lockstep.
const VERSION = JSON.parse(
  readFileSync(new URL("./package.json", import.meta.url), "utf8"),
).version
// Going-forward default; override with FIGS_ENDPOINT or .figs/config.json endpoint
// (e.g. FIGS_ENDPOINT=http://localhost:3000 for local dev).
const DEFAULT_ENDPOINT = "https://app.figs.so"

const repoDir = join(process.cwd(), ".figs")
const globalDir = join(homedir(), ".figs")
const globalCreds = join(globalDir, "credentials.json")
const cmd = process.argv[2] ?? "help"
const JSON_OUT = process.argv.includes("--json")
const WANTS_HELP = process.argv.slice(2).some((a) => a === "-h" || a === "--help")

/**
 * Command registry — single source for dispatch, `figs help`, and per-command
 * flag validation. `flags` lists the flags a command accepts (beyond the global
 * `-h`/`--help`); an unrecognized flag is rejected rather than silently ignored.
 */
const COMMANDS = {
  status: {
    args: "[--json]",
    flags: ["--json"],
    desc: "show login / workspace / agent state",
    eg: "figs status --json",
  },
  login: {
    args: "[<token>]",
    flags: [],
    desc: "log in — browser device-flow, or save a pasted token",
    more: [
      "no arg → device flow: opens a browser for a human to approve (you never see the token).",
      "<token> → save a token you already have to ~/.figs/credentials.json.",
    ],
    eg: "figs login",
  },
  logout: { args: "", flags: [], desc: "remove the locally-saved token (~/.figs/credentials.json)" },
  workspaces: {
    args: "[--json]",
    flags: ["--json"],
    desc: "list your workspaces (read-only; shows the slug)",
    eg: "figs workspaces",
  },
  init: {
    args: "[--workspace <slug-or-id>] [--endpoint <url>]",
    flags: ["--workspace", "--endpoint"],
    desc: "scaffold .figs/ here (identity + charter/contract/guide templates)",
    more: [
      "--workspace takes a slug (resolved to its UUID) or a raw UUID — get it from `figs workspaces`.",
      "Omit --workspace and (logged in) it lists your workspaces so you can re-run with the right one.",
      "Never clobbers: an existing agent.json / CONTRACT.md / GUIDE.md / outbox is left exactly as-is.",
    ],
    eg: "figs init --workspace acme-corp",
  },
  doctor: { args: "", flags: ["--json"], desc: "validate .figs/ against the live contract before pushing" },
  push: {
    args: "",
    flags: [],
    desc: "publish .figs/ — spine to /api/ingest, artifacts to /api/artifacts",
    more: ["Idempotent (records fold by id). Exits non-zero if an artifact upload is rejected."],
    eg: "figs push",
  },
  version: { args: "", flags: [], desc: "print the CLI version and check for updates" },
  help: { args: "[<command>]", flags: [], desc: "show this help, or detailed help for one command" },
}

/** Reject unknown flags for a command (don't silently ignore an agent's typo). */
function checkFlags(name) {
  const allowed = new Set([...(COMMANDS[name].flags ?? []), "-h", "--help"])
  for (const tok of process.argv.slice(3)) {
    if (tok.startsWith("-") && tok !== "-" && tok !== "--") {
      const f = tok.split("=")[0]
      if (!allowed.has(f)) {
        die(`unknown flag "${f}" for \`figs ${name}\` — run \`figs ${name} --help\``)
      }
    }
  }
}

function die(msg) {
  console.error(`figs: ${msg}`)
  process.exit(1)
}
function readJson(path, fallback) {
  return existsSync(path) ? JSON.parse(readFileSync(path, "utf8")) : fallback
}
/** Read a flag value — supports both `--name value` and `--name=value`. */
function flag(name) {
  const args = process.argv.slice(2)
  for (let i = 0; i < args.length; i++) {
    if (args[i] === name) return args[i + 1]
    if (args[i].startsWith(`${name}=`)) return args[i].slice(name.length + 1)
  }
  return undefined
}
function getToken() {
  return process.env.FIGS_TOKEN || readJson(globalCreds, {}).token
}
function resolveEndpoint() {
  const cfg = readJson(join(repoDir, "config.json"), {})
  return (process.env.FIGS_ENDPOINT || cfg.endpoint || DEFAULT_ENDPOINT).replace(
    /\/+$/,
    "",
  )
}
const REQUEST_TIMEOUT_MS = 30000
/** `fetch` with a hard timeout so a hung server never stalls the agent. */
async function fetchT(url, opts = {}) {
  const ctrl = new AbortController()
  const t = setTimeout(() => ctrl.abort(), REQUEST_TIMEOUT_MS)
  try {
    return await fetch(url, { ...opts, signal: ctrl.signal })
  } finally {
    clearTimeout(t)
  }
}
/** Human reason for a thrown fetch error (timeout vs. network). */
function netReason(e) {
  if (e?.name === "AbortError") return `timed out after ${REQUEST_TIMEOUT_MS / 1000}s`
  return e?.cause?.code || e?.code || e?.message || "network error"
}
/** Low-level request — returns { ok, status, data }, never throws/exits. */
async function request(method, path, body, token = getToken()) {
  const base = resolveEndpoint()
  let res
  try {
    res = await fetchT(`${base}${path}`, {
      method,
      headers: {
        "content-type": "application/json",
        ...(token ? { "x-figs-token": token } : {}),
      },
      body: body ? JSON.stringify(body) : undefined,
    })
  } catch (e) {
    // Unreachable host / DNS / timeout — degrade, don't crash.
    return { ok: false, status: 0, data: { error: `cannot reach ${base} (${netReason(e)})` } }
  }
  const text = await res.text()
  let data
  try {
    data = text ? JSON.parse(text) : {}
  } catch {
    data = { raw: text }
  }
  return { ok: res.ok, status: res.status, data }
}
/** Authenticated request that exits with a clear message on failure. */
async function api(method, path, body) {
  if (!getToken()) die("not logged in — run `figs login` (or set FIGS_TOKEN)")
  const r = await request(method, path, body)
  if (!r.ok) die(`${path} failed (${r.status}): ${r.data.error ?? r.data.raw ?? ""}`)
  return r.data
}

/**
 * Compare two semver strings → -1 | 0 | 1, or **null** if either is unparseable.
 * Returning null (rather than guessing) lets the caller skip the check instead of
 * failing closed on a malformed server-provided version — a bad `min` must never
 * lock an agent out of pushing.
 */
function cmpSemver(a, b) {
  const pa = String(a).split(".").map((n) => parseInt(n, 10))
  const pb = String(b).split(".").map((n) => parseInt(n, 10))
  for (let i = 0; i < 3; i++) {
    const x = pa[i] ?? 0
    const y = pb[i] ?? 0
    if (Number.isNaN(x) || Number.isNaN(y)) return null
    if (x !== y) return x < y ? -1 : 1
  }
  return 0
}
/**
 * Cached (daily) compatibility check — off the hot path. `hardFail` exits when
 * below the server's compatible `min`. Network failure is ignored (never blocks
 * on a transient outage).
 */
async function checkVersion({ force = false, hardFail = false } = {}) {
  const cachePath = join(globalDir, "version-check.json")
  let info = readJson(cachePath, {})
  const stale = !info.checkedAt || Date.now() - info.checkedAt > 86400000
  if (force || stale) {
    const r = await request("GET", "/api/version")
    if (r.ok) {
      info = { ...r.data, checkedAt: Date.now() }
      try {
        mkdirSync(globalDir, { recursive: true })
        writeFileSync(cachePath, JSON.stringify(info, null, 2) + "\n")
      } catch {
        /* cache best-effort */
      }
    }
  }
  const min = info?.cli?.min
  // cmpSemver returns null on an unparseable version → skip (never fail closed).
  if (min && cmpSemver(VERSION, min) === -1) {
    const msg = `figs CLI ${VERSION} is below the minimum ${min} — upgrade: npx @figs-so/cli@latest`
    if (hardFail) die(msg)
    console.warn(`figs: ! ${msg}`)
  }
}

/** `figs help [cmd]` — top-level usage, or one command's detail. */
function printHelp(name) {
  const pad = 36
  if (name && name !== "-h" && name !== "--help") {
    const c = COMMANDS[name]
    if (!c) {
      console.log(`figs: no such command "${name}"\n`)
      return printHelp()
    }
    console.log(`Usage: figs ${name}${c.args ? " " + c.args : ""}\n`)
    console.log(`  ${c.desc}`)
    if (c.more) for (const line of c.more) console.log(`  ${line}`)
    if (c.eg) console.log(`\n  e.g.  ${c.eg}`)
    return
  }
  console.log("figs — publish your AI agent's state to Figs (https://figs.so)\n")
  console.log("Usage: figs <command> [options]\n")
  console.log("Commands:")
  for (const [n, c] of Object.entries(COMMANDS)) {
    console.log(`  ${`${n} ${c.args}`.trim().padEnd(pad)} ${c.desc}`)
  }
  console.log("\nGlobal flags:")
  console.log(`  ${"-h, --help".padEnd(pad)} show help (or \`figs help <command>\`)`)
  console.log(`  ${"-v, --version".padEnd(pad)} print the CLI version`)
  console.log("\nEnvironment:")
  console.log(`  ${"FIGS_ENDPOINT".padEnd(pad)} override the API endpoint (e.g. http://localhost:3000)`)
  console.log(`  ${"FIGS_TOKEN".padEnd(pad)} use this token instead of ~/.figs/credentials.json`)
  console.log(`\nEndpoint: ${resolveEndpoint()}`)
  console.log(`Guide:    ${resolveEndpoint()}/llms.txt`)
}

if (cmd === "help" || cmd === "-h" || cmd === "--help") printHelp(process.argv[3])
else if (cmd === "version" || cmd === "--version" || cmd === "-v" || cmd === "-V") {
  console.log(VERSION)
  await checkVersion({ force: true })
} else if (WANTS_HELP) printHelp(cmd)
else if (COMMANDS[cmd]) {
  checkFlags(cmd) // reject unknown flags before running
  if (cmd === "login") await login(process.argv[3])
  else if (cmd === "logout") logout()
  else if (cmd === "status") await status()
  else if (cmd === "workspaces") await workspaces()
  else if (cmd === "init") await init()
  else if (cmd === "doctor") await doctor()
  else if (cmd === "push") await push()
} else {
  console.error(`figs: unknown command "${cmd}" — run \`figs help\` for usage`)
  process.exit(1)
}

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms))
}
function saveToken(token) {
  // A bearer token must not be group/other-readable: dir 0700, file 0600.
  mkdirSync(globalDir, { recursive: true, mode: 0o700 })
  writeFileSync(globalCreds, JSON.stringify({ token }, null, 2) + "\n", { mode: 0o600 })
  // Enforce perms even if the dir/file pre-existed with looser modes (mode on
  // write only applies at creation).
  try {
    chmodSync(globalDir, 0o700)
    chmodSync(globalCreds, 0o600)
  } catch {
    /* best-effort — non-POSIX filesystems */
  }
}

// Best-effort: pop the approval page in the user's default browser so they only
// have to click Approve. Silent no-op when it can't (headless / remote / CI) —
// the link is always printed above as the fallback. Detached + unref'd so it
// never blocks or ties the polling loop to the browser process.
function openBrowser(url) {
  try {
    const [cmd, args] =
      process.platform === "darwin"
        ? ["open", [url]]
        : process.platform === "win32"
          ? ["cmd", ["/c", "start", "", url]]
          : ["xdg-open", [url]]
    const child = spawn(cmd, args, { stdio: "ignore", detached: true })
    child.on("error", () => {}) // swallow ENOENT / no opener available
    child.unref()
  } catch {
    /* ignore — the printed link is the fallback */
  }
}

/**
 * `figs login` → device flow: opens the approval page in the user's browser
 * (the printed link is the fallback); the human clicks Approve and the agent
 * never handles the token. `figs login <token>` → save a pasted token (fallback).
 */
async function login(token) {
  if (token) {
    saveToken(token)
    console.log("figs: ✓ token saved to ~/.figs/credentials.json")
    return
  }

  const start = await request("POST", "/api/device/start")
  if (!start.ok) die(`could not start login (${start.status})`)
  const d = start.data
  console.log("figs: opening your browser to approve this CLI — just click Approve there.")
  console.log(`        if it doesn't open, visit: ${d.verification_uri_complete}`)
  console.log(`        (or go to ${d.verification_uri} and enter code: ${d.user_code})`)
  openBrowser(d.verification_uri_complete)
  console.log("figs: waiting for approval…")

  const deadline = Date.now() + (d.expires_in ?? 600) * 1000
  const wait = (d.interval ?? 5) * 1000
  while (Date.now() < deadline) {
    await sleep(wait)
    const r = await request("POST", "/api/device/poll", { device_code: d.device_code })
    const status = r.data?.status
    if (status === "approved" && r.data.token) {
      saveToken(r.data.token)
      console.log("figs: ✓ authorized — token saved to ~/.figs/credentials.json")
      return
    }
    if (status === "denied") die("authorization denied")
    if (status === "expired") die("code expired — run `figs login` again")
    if (status === "already_claimed") {
      die("this login was already completed (on another run) — run `figs status` to check; re-run `figs login` if no token was saved")
    }
    if (status === "not_found") die("login code not found — run `figs login` again")
    // pending → keep polling
  }
  die("timed out waiting for approval — run `figs login` again")
}

/**
 * `figs logout` — remove the locally-saved token (`~/.figs/credentials.json`).
 * This only clears *this machine's* copy; the token still exists server-side
 * until you revoke it in Settings. A token supplied via the FIGS_TOKEN env var
 * can't be removed here (unset the env var to fully log out).
 */
function logout() {
  if (existsSync(globalCreds)) {
    try {
      rmSync(globalCreds)
    } catch (e) {
      die(`could not remove ${globalCreds}: ${e?.message || e}`)
    }
    console.log("figs: ✓ logged out — removed ~/.figs/credentials.json")
  } else {
    console.log("figs: not logged in — no ~/.figs/credentials.json to remove")
  }
  if (process.env.FIGS_TOKEN) {
    console.warn(
      "figs: ! FIGS_TOKEN is still set in your environment — `unset FIGS_TOKEN` to fully log out",
    )
  }
  console.log(
    `        the token still exists server-side — revoke it at ${resolveEndpoint()}/settings`,
  )
}

/** Show where setup stands — login, workspace, charter. Drives the agent's next step. */
async function status() {
  const token = getToken()
  const cfg = readJson(join(repoDir, "config.json"), null)
  const hasAgent = existsSync(join(repoDir, "agent.json"))
  const hasContract = existsSync(join(repoDir, "CONTRACT.md"))
  const endpoint = resolveEndpoint()

  let loggedIn = false
  let list = null
  let account = null
  let unreachable = false
  if (token) {
    const r = await request("GET", "/api/workspaces", null, token)
    loggedIn = r.ok
    unreachable = r.status === 0
    if (r.ok) {
      list = r.data.workspaces ?? []
      account = r.data.user ?? null // null on a pre-account server
    }
  }

  if (JSON_OUT) {
    console.log(
      JSON.stringify(
        {
          version: VERSION,
          endpoint,
          loggedIn,
          account: account
            ? { id: account.id, email: account.email, name: account.name }
            : null,
          workspaces: list?.map((w) => ({ id: w.id, name: w.name, role: w.role })),
          config: cfg ? { workspaceId: cfg.workspaceId, agentId: cfg.agentId } : null,
          agentJson: hasAgent,
          contractMd: hasContract,
        },
        null,
        2,
      ),
    )
    return
  }

  const row = (k, v) => console.log(`  ${(k + ":").padEnd(12)} ${v}`)
  console.log("figs status")
  row(
    "logged in",
    loggedIn
      ? `yes (${list.length} workspace${list.length === 1 ? "" : "s"})`
      : unreachable
        ? `can't reach ${endpoint}`
        : token
          ? "token invalid — run `figs login`"
          : "no — run `figs login`",
  )
  if (loggedIn) {
    row(
      "account",
      account?.email
        ? `${account.email}${account.name ? ` (${account.name})` : ""}`
        : "—",
    )
  }
  row(
    "workspace",
    cfg?.workspaceId
      ? cfg.workspaceId
      : "not initialized — run `figs init --workspace <id>`",
  )
  row("agent.json", hasAgent ? "present (identity)" : "missing — author .figs/agent.json")
  row(
    "contract",
    hasContract
      ? "present (activity) — follow it"
      : "none yet — Activity is optional, agree it with your user",
  )
  row("endpoint", endpoint)
  row("cli", VERSION)
}

/**
 * List the user's workspaces (read-only). Creating a workspace is a human,
 * web-side action — the agent only ever joins one it was pointed at. Surfaces
 * the slug, which is what `figs init --workspace <slug>` takes.
 */
async function workspaces() {
  const { workspaces: list = [] } = await api("GET", "/api/workspaces")
  if (JSON_OUT) return void console.log(JSON.stringify(list, null, 2))
  if (list.length === 0) {
    console.log("figs: no workspaces yet — create one in the Figs web app, then re-run.")
    return
  }
  console.log(`figs: ${list.length} workspace${list.length === 1 ? "" : "s"}`)
  for (const w of list) {
    console.log(`  ${String(w.role).padEnd(6)} ${w.slug}  —  ${w.name}`)
  }
  console.log("  → figs init --workspace <slug>")
}

function isUuid(s) {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
    String(s),
  )
}

/**
 * The local `.figs/GUIDE.md` is a thin orientation breadcrumb (safe to
 * regenerate) — the full, always-current guide + schema is served at
 * `${endpoint}/llms.txt`, and the agent's own standing agreement lives in the
 * precious, agent-authored `.figs/CONTRACT.md` (which `init` never touches).
 */
function guideStub(endpoint) {
  return `<!-- Written by \`figs init\` (safe to regenerate). Orientation only — the full
     guide lives at the URL below; your own contract lives in CONTRACT.md. -->
# Figs — this folder

This repo publishes to **Figs** (your manager's read-only window into what you do).

- **Full guide + schema → ${endpoint}/llms.txt** — read this first.
- **Your contract → ./CONTRACT.md** — what you publish / hold back (you + your user author it).
- **Identity → config.json** (committed) · **charter → agent.json** (you write).
- **Stay visible:** keep the \`figs:begin\`…\`figs:end\` block in the instruction file you load every
  session (CLAUDE.md/AGENTS.md/…). It's what brought you back here — don't remove it. (Phase-1 setup; see /llms.txt.)

**Where are you?** You may be reading this at any time — don't assume you're starting fresh. Run
\`figs status\` and check \`.figs/\` before acting:
  • not set up yet → author \`.figs/agent.json\`, then \`figs doctor\` && \`figs push\` to appear (Identity).
  • CONTRACT.md present → follow it; keep publishing what it says.
  • no CONTRACT.md yet → agree with your user what work to surface (Activity) — see ${endpoint}/llms.txt.

Commit config.json + agent.json + CONTRACT.md + this file. runs.jsonl / asks.jsonl / artifacts/
are a gitignored outbox. The token is the human's job — never generate one yourself.
`
}

/**
 * A starter `agent.json` — written by `figs init` only when none exists. The
 * `<…>` values are placeholders the agent fills in by reading its own repo;
 * `figs doctor` refuses to bless a charter that still has them. `name` defaults
 * to the folder name (a sensible first guess), `id` is intentionally absent —
 * the CLI attaches the identity UUID from config.json on push.
 */
function agentJsonStub(name) {
  return (
    JSON.stringify(
      {
        name,
        role: "<one line — what you are>",
        status: "in_dev",
        mandate: "<one sentence — what you are accountable for>",
        org: { department: "<your team / department>" },
        runtime: "<what runs you, e.g. Claude Code>",
        cadence: "<on-demand · weekly · monthly · …>",
        responsibilities: ["<an area of work you own — list a few, or use steps>"],
        properties: [{ k: "<fact>", v: "<value>" }],
      },
      null,
      2,
    ) + "\n"
  )
}

/** A starter activity contract — written by `figs init` only when none exists. */
function contractStub(name) {
  return `# Activity contract — ${name} on Figs

What this agent surfaces to Figs vs. holds back. **Agree it with your user** — this is the
deliberate Activity step, not something to do mechanically. See \`.figs/GUIDE.md\` for the why.

> **Maintain:** edit when the surfacing agreement changes (a new stream, a sensitivity change).
> Keep it honest to what you actually push.

## What I surface

| Stream | Surface? | Content |
|--------|----------|---------|
| **runs** | <yes/no> | one line per run — what I did, de-identified scope, the headline result + status. |
| **artifacts** | <yes/no> | the report(s) a run produced. |
| **asks** | when real | genuine blockers / decisions / sign-offs / FYIs for my manager. 0 is a fine number. |

## What I never surface

Raw user content — ever. Plus, for this agent: <anything sensitive to its domain>. Use
**de-identified labels** (\`<scope>-01\`), never customer or system names.
`
}

/**
 * Find string values still left as `<…>` template placeholders, with their JSON
 * path. Used by `figs doctor` to block publishing a half-filled charter. Matches
 * a value that is *entirely* a placeholder (e.g. "<one line — what you are>") so
 * real content containing stray angle brackets isn't flagged.
 */
function findPlaceholders(obj) {
  const out = []
  const walk = (v, path) => {
    if (typeof v === "string") {
      if (/^<.*>$/.test(v.trim())) out.push({ path: path || "(root)", value: v })
    } else if (Array.isArray(v)) {
      v.forEach((x, i) => walk(x, `${path}[${i}]`))
    } else if (v && typeof v === "object") {
      for (const [k, x] of Object.entries(v)) walk(x, path ? `${path}.${k}` : k)
    }
  }
  walk(obj, "")
  return out
}

/**
 * Resolve which workspace this `.figs/` belongs to. `--workspace` is optional:
 *  - given a UUID  → use it as-is (no network).
 *  - given a slug  → resolve to its UUID via the API (needs auth).
 *  - omitted       → reuse the one already in config.json (idempotent re-init),
 *                    else list the user's workspaces and have them re-run with one
 *                    (the agent drives the choice — we never silently pick).
 * Returns the workspace UUID, or exits with an actionable message.
 */
async function resolveWorkspaceId(workspaceArg, endpoint) {
  if (workspaceArg) {
    if (isUuid(workspaceArg)) return workspaceArg
    if (!getToken()) {
      die("not logged in — run `figs login` first (resolving a workspace slug needs auth; or pass the workspace UUID)")
    }
    const r = await request("GET", "/api/workspaces", null, getToken())
    if (!r.ok) {
      die(`could not resolve workspace "${workspaceArg}" (${r.status}): ${r.data.error ?? r.data.raw ?? ""}`)
    }
    const list = r.data.workspaces ?? []
    const match = list.find((w) => w.slug === workspaceArg || w.id === workspaceArg)
    if (!match) die(`no workspace matching "${workspaceArg}" — run \`figs workspaces\` to see yours`)
    return match.id
  }

  // No --workspace: a re-init keeps the workspace already on file.
  const existing = readJson(join(repoDir, "config.json"), null)
  if (existing?.workspaceId) return existing.workspaceId

  // First-time init with no workspace named — list them so the agent can re-run.
  if (!getToken()) {
    die("which workspace? run `figs login` first so I can list them, then `figs init --workspace <slug>` (or pass a workspace UUID directly)")
  }
  const r = await request("GET", "/api/workspaces", null, getToken())
  if (!r.ok) die(`could not list workspaces (${r.status}): ${r.data.error ?? r.data.raw ?? ""}`)
  const list = r.data.workspaces ?? []
  if (list.length === 0) {
    die(`no workspaces yet — create one at ${endpoint}, then re-run \`figs init --workspace <slug>\``)
  }
  console.log("figs: which workspace? re-run init with one of these:")
  for (const w of list) console.log(`        figs init --workspace ${w.slug}   (${w.name})`)
  process.exit(1)
}

async function init() {
  const endpoint = (flag("--endpoint") || resolveEndpoint()).replace(/\/+$/, "")
  const workspaceId = await resolveWorkspaceId(flag("--workspace"), endpoint)

  // config.json (identity + destination) is always (re)written — it's the one
  // file the CLI owns. A re-init reuses the existing identity UUID so every
  // runner of this repo pushes to the same agent.
  const existing = readJson(join(repoDir, "config.json"), null)
  const agentId = existing?.agentId || randomUUID()
  mkdirSync(repoDir, { recursive: true })
  writeFileSync(
    join(repoDir, "config.json"),
    JSON.stringify({ endpoint, workspaceId, agentId }, null, 2) + "\n",
  )

  // Everything else is scaffolded create-if-missing — `figs init` gives a fresh
  // repo a complete, ready-to-fill `.figs/`, and never clobbers an agent's
  // authored charter/contract/guide or its activity outbox.
  const created = []
  const ensure = (rel, contents) => {
    const p = join(repoDir, rel)
    if (existsSync(p)) return false
    writeFileSync(p, contents)
    created.push(rel)
    return true
  }
  ensure(
    ".gitignore",
    [
      "# Figs — commit config.json + agent.json + CONTRACT.md + GUIDE.md.",
      "# Activity is a transient outbox: emitted per run, aggregated remotely.",
      "runs.jsonl",
      "asks.jsonl",
      "artifacts/",
      "credentials.json",
      "",
    ].join("\n"),
  )
  ensure("GUIDE.md", guideStub(endpoint))
  const name = basename(process.cwd())
  const charterCreated = ensure("agent.json", agentJsonStub(name))
  ensure("CONTRACT.md", contractStub(name))
  ensure("runs.jsonl", "")
  ensure("asks.jsonl", "")
  mkdirSync(join(repoDir, "artifacts"), { recursive: true })

  console.log(
    `figs: ✓ .figs/ ready — config.json written (agentId ${agentId}, workspace ${workspaceId})`,
  )
  if (created.length) console.log(`        scaffolded: ${created.join(", ")}`)
  if (charterCreated) {
    console.log(
      "        Phase 1: fill in .figs/agent.json — it's a template; replace the <…> placeholders",
    )
    console.log(
      "        (`figs doctor` flags any you miss), then `figs doctor` && `figs push` to appear.",
    )
  } else {
    console.log(
      "        Your charter (.figs/agent.json) is already here — `figs doctor` && `figs push` to publish.",
    )
  }
  console.log(
    "        Anchor Figs in the file you load every session (CLAUDE.md/AGENTS.md/…): paste the",
  )
  console.log(`        figs:begin block from ${endpoint}/llms.txt, or future sessions forget Figs.`)
  console.log(
    "        Commit config.json + agent.json + CONTRACT.md + GUIDE.md; never commit credentials.json.",
  )
  console.log(`        Full guide: ${endpoint}/llms.txt`)
}

/** Validate the local .figs/ payload against the contract — no write. */
async function doctor() {
  // Local checks first (no token/network needed) — fail fast and offline.
  if (!existsSync(repoDir)) die("no .figs/ here — run `figs init` first")
  const config = readJson(join(repoDir, "config.json"), {})
  if (!config.workspaceId || !config.agentId) {
    die("config missing workspaceId/agentId — run `figs init`")
  }
  const agentJson = readJson(join(repoDir, "agent.json"), null)
  if (!agentJson) die("missing .figs/agent.json — author it first (see .figs/GUIDE.md)")

  // Refuse to bless a charter that still has `<…>` template placeholders — `figs
  // init` scaffolds them, and pushing them would publish "<one line — what you
  // are>" to the org chart. This is the "not ready to push" signal.
  const placeholders = findPlaceholders(agentJson)
  if (placeholders.length) {
    console.log("figs: ✗ .figs/agent.json still has template placeholders — fill these in before pushing:")
    for (const p of placeholders) console.log(`  ${p.path}: ${p.value}`)
    console.log("  (replace the <…> values by reading your own repo, then re-run `figs doctor`)")
    process.exit(1)
  }

  if (!getToken()) die("not logged in — run `figs login`")
  const r = await api("POST", "/api/validate", {
    workspaceId: config.workspaceId,
    agent: { ...agentJson, id: config.agentId },
    runs: foldById(readJsonl("runs.jsonl")),
    asks: foldById(readJsonl("asks.jsonl")),
  })
  if (r.ok) {
    console.log("figs: ✓ .figs/ is valid — ready to push")
    return
  }
  if (JSON_OUT) {
    console.log(JSON.stringify(r.issues, null, 2))
  } else {
    console.log("figs: ✗ validation issues:")
    for (const i of r.issues) {
      console.log(`  ${i.path || "(root)"}: ${i.message}`)
      // The server quotes the canonical shape for the field you got wrong —
      // show it so you don't have to re-read the guide to fix it.
      if (i.expected) console.log(`      expected e.g. ${i.expected}`)
    }
    console.log(`  (full shapes + a valid example: ${resolveEndpoint()}/llms.txt)`)
  }
  process.exit(1)
}

async function push() {
  const token = process.env.FIGS_TOKEN || readJson(globalCreds, {}).token
  if (!token) die("not logged in — run `figs login` (or set FIGS_TOKEN)")
  await checkVersion({ hardFail: true })
  if (!existsSync(repoDir)) {
    die("no .figs/ here — run `figs init` first")
  }
  const config = readJson(join(repoDir, "config.json"), {})
  if (!config.workspaceId || !config.agentId) {
    die("config missing workspaceId/agentId — run `figs init`")
  }
  const endpoint =
    process.env.FIGS_ENDPOINT || config.endpoint || DEFAULT_ENDPOINT

  const agentJson = readJson(join(repoDir, "agent.json"), null)
  if (!agentJson) die("missing .figs/agent.json")
  const agent = { ...agentJson, id: config.agentId }
  const runs = foldById(readJsonl("runs.jsonl"))
  const asks = foldById(readJsonl("asks.jsonl"))

  const base = endpoint.replace(/\/+$/, "")
  let res
  try {
    res = await fetchT(`${base}/api/ingest`, {
      method: "POST",
      headers: { "content-type": "application/json", "x-figs-token": token },
      body: JSON.stringify({ workspaceId: config.workspaceId, agent, runs, asks }),
    })
  } catch (e) {
    die(`push failed — cannot reach ${base} (${netReason(e)})`)
  }
  const text = await res.text()
  if (!res.ok) die(`push failed (${res.status}): ${text}`)
  console.log(
    `figs: ✓ pushed ${agent.name ?? agent.id} — ${runs.length} runs, ${asks.length} asks`,
  )
  // The wow-moment link — relay this to your human so they can see the agent.
  console.log(`       view at ${base}/w/${config.workspaceId}`)

  await pushArtifacts(base, token, config, runs, asks)
}

/**
 * Upload the files referenced by runs (run.artifact) and ask refs (refs[].artifact).
 * The spine ingest is JSON-only; artifacts go to a separate endpoint that stores
 * them content-addressed (an unchanged file is skipped server-side). Content is
 * sent base64-encoded so any type — html, markdown, text, json, images — survives.
 * A **server rejection** (auth/size/etc.) is fatal: it prints ✗ and exits non-zero
 * so the agent never believes a report published when it didn't (esp. the ~3 MB
 * cap → 413). A **missing local file** is only a warning — that's the agent
 * referencing an artifact it didn't actually produce, not a publish failure.
 */
async function pushArtifacts(base, token, config, runs, asks) {
  const refNames = (asks ?? []).flatMap((a) =>
    (a.refs ?? []).map((r) => r.artifact),
  )
  const names = [
    ...new Set([...runs.map((r) => r.artifact), ...refNames].filter(Boolean)),
  ]
  if (names.length === 0) return

  let uploaded = 0
  let unchanged = 0
  let missing = 0
  let failed = 0
  for (const name of names) {
    const p = join(repoDir, "artifacts", name)
    if (!existsSync(p)) {
      console.warn(`figs: ! artifact missing, skipped: artifacts/${name}`)
      missing++
      continue
    }
    const content = readFileSync(p).toString("base64")
    let res
    try {
      res = await fetchT(`${base}/api/artifacts/upload`, {
        method: "POST",
        headers: { "content-type": "application/json", "x-figs-token": token },
        body: JSON.stringify({
          workspaceId: config.workspaceId,
          agentId: config.agentId,
          name,
          content,
        }),
      })
    } catch (e) {
      console.error(`figs: ✗ artifact upload failed ${name}: ${netReason(e)}`)
      failed++
      continue
    }
    if (!res.ok) {
      const t = await res.text().catch(() => "")
      const hint =
        res.status === 413 ? " — too large (>3 MB); compress or split it" : ""
      console.error(
        `figs: ✗ artifact upload failed (${res.status}) ${name}${hint}${t ? `: ${t}` : ""}`,
      )
      failed++
      continue
    }
    const body = await res.json().catch(() => ({}))
    if (body.unchanged) unchanged++
    else uploaded++
  }
  console.log(
    `figs: ${failed ? "✗" : "✓"} artifacts — ${uploaded} uploaded, ${unchanged} unchanged` +
      (missing ? `, ${missing} missing` : "") +
      (failed ? `, ${failed} failed` : ""),
  )
  // The spine already landed; signal a non-zero exit so an agent's run loop can
  // catch that an artifact the manager needs to read did not publish.
  if (failed) process.exit(1)
}

function readJsonl(name) {
  const p = join(repoDir, name)
  if (!existsSync(p)) return []
  const out = []
  readFileSync(p, "utf8")
    .split("\n")
    .forEach((line, i) => {
      const s = line.trim()
      if (!s) return
      try {
        out.push(JSON.parse(s))
      } catch {
        die(`malformed JSON in .figs/${name} line ${i + 1}: ${s.slice(0, 80)}`)
      }
    })
  return out
}

/** Fold append-only records by id — latest line wins. */
function foldById(rows) {
  const m = new Map()
  for (const r of rows) m.set(r.id, { ...(m.get(r.id) ?? {}), ...r })
  return [...m.values()]
}
